### ISSUE TITLE
README.md Docker container building method has been invalidated in v7.0+

### ISSUE THREAD

**Issue by nobk** [be5invis/Iosevka#1105]
docker run -e FONT_VERSION=7.0.3 -it -v $(pwd):/build avivace/iosevka-build
will report error stop, which is reproducible.
docker run -e FONT_VERSION=6.1.3 -it -v $(pwd):/build avivace/iosevka-build
still working.
* Your font version: 7.0.3

**Comment by AdrianCollado** [comment]
I also had an issue building, though I don't believe it is related specifically to Docker. I was able to fix my build by editing the `package.json` file to change both `ot-builder` packages to 1.0.8 rather than the versions they specified. I was able to build fonts 2 days ago, and those packages were updated today, so my guess is something in those packages broke the build across the board.

**Comment by AdrianCollado** [comment]
One other note - `otb-ttc-bundle` wasn't being given any of the generated TTFs, so I had to change that command to hardcode the generated path.

**Comment by be5invis** [comment]
@nobk I do not own docker images. Please file an issue to the owner.
@AdrianCollado 1.0.9 worked fine on my system (not through Docker though).

Resolve as external.

**Comment by nobk** [comment]
In the end, I found that the issue was not caused by docker builder, but the `a = "double-storey"` in my customized configuration file. v7.0+ changed the name of `a = "double-storey"` glyph.
