### ISSUE TITLE
Add Go Mono style

### ISSUE THREAD

**Issue by cprog** [be5invis/Iosevka#1109]
Hello,

I would like to suggest adding Go mono as a style from which to inherit when someone makes a custom build.
Thank you in advance if this is possible.

**Comment by be5invis** [comment]
Well, there's only one unused tag (`ss19`) and I'd like to reserve it for something in the future. Also, Go Mono looks more like a serif with high contrast, which is significantly different from Iosevka and Iosevka Slab.
Marks as Needs Justification

**Comment by VladWinner** [comment]
Actually this makes much less sense than adding Cascadia Code/Mono style inspired by source font that containing open apertures like most of source fonts from current stylistic sets.
I agree, "Go Mono Style" even as a "Slab + SS02/SS03 hybrid" compilation doesn't look anything like Go Mono because of Iosevka's design.
