### ISSUE TITLE
Micro sign/Greek lowercase mu disambiguation

### ISSUE THREAD

**Issue by acarasimon96** [be5invis/Iosevka#1220]
- [x] The requested variant shape does not go too far away from Iosevka's design.
- [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [x] At least two monospace/programming fonts, created by different designers, supported the requested variant. Provide images below.

------

Now that a tailless variant of Greek lowercase mu (μ) has been implemented in v10.1.0 thanks to #1211, I would like to see an option to distinguish between that character and the micro sign. In most fonts, both programming/monospaced and proportional ones, only one glyph is used for both characters. There are a few fonts that do make the distinction between them, often by adding a tail to Greek lowercase mu.

Liberation Mono/Cousine:
![image](https://user-images.githubusercontent.com/17580077/132965908-4a3d4f57-7bb7-4245-b6a6-4df0c7265320.png)

Anonymous Pro:
![image](https://user-images.githubusercontent.com/17580077/132966128-abd7aca8-eb10-4ef9-bb1e-cdb4b4cdf20f.png)

B612 Mono (an interesting case where the glyphs are swapped but still distinguish between each other):
![image](https://user-images.githubusercontent.com/17580077/132966151-ec56ad52-26ff-480e-ae82-5039ee7dbf6e.png)

Note that I used [programmingfonts.org](https://www.programmingfonts.org) for all screenshots above.

**Comment by be5invis** [comment]
I am curious about whether such difference is intensional, or just because `mu` and `microSign` are designed at different times...

**Comment by acarasimon96** [comment]
I'm more interested in being able for `mu` and `microSign` to have their own glyphs as a personal preference, similar to the screenshots above. I think that Greek users who use both characters in their code or writing (for example, lengths in micrometers in a science report) might benefit the most from this. Either way, I believe your question is worthy of doing some fun research. :smile:

**Comment by ucctheblend** [comment]
Is there any practical reason to have them look different? If I understand correctly, the micro sign is for compatibility, and the letter mu is preferred. It seems to be merely a technical artifact, rather than being called for by any actual need in usage.

According to http://www.unicode.org/reports/tr25/:

> Some  Greek  letters  are  encoded  elsewhere  as  technical  symbols.  These  include  U+00B5 μ MICRO SIGN, U+2126 Ω OHM SIGN, and several characters among the APL functional symbols in the  Miscellaneous  Technical  block. U+03A9 Ω GREEK  LETTER  CAPITAL  OMEGA  is  the  canonical equivalent  of  U+2126 Ω and its use is preferred. _Micro  sign_  is  included  in  several  parts  of ISO/IEC  8859,  and  therefore  supported  in  many  legacy  environments  where  U+03BC μ GREEK LETTER SMALL MU is not available. Implementations therefore need to be able to recognize the micro sign, even though U+03BC μ is the preferred character in a Unicode context.

If they are distinguished, one would imagine that the other so called duplicates (e.g. ohm, angstrom, kelvin, alef, etc) need to look distinct as well, but that doesn't seem very practicable.

**Comment by clsn** [comment]
It's interesting; I was just looking.  ANGSTROM SIGN and KELVIN SIGN and OHM SIGN are all *canonically* equivalent to their lookalike characters.  Unicode rules expect you to treat them exactly the same, they really are, in some sense, the same.  But MICRO SIGN is only *compatibility* equivalent to GREEK SMALL LETTER MU.  Why?  I don't know.  But it is so.  You really can't/shouldn't make angstrom, kelvin, ohm distinct from their "normal" letter forms.  But maybe MICRO SIGN can be.  (ALEF is also not canonically equivalent, and really can't be, because it has different directionality.)

**Comment by johnfactotum** [comment]
I guess for the alef, for example, it might make some sense to have distinct designs, since the two signs are used in distinct typographical contexts. Another example might be the letter sigma and the summation symbol. They are used in different contexts, even though conceptually they are, in a sense, the same.

So it seems that, typographically speaking, it _does_ make sense to have tailed mu and straight micro sign: Historically, the Greek alphabet is usually more "script-y" than its Latin counterpart (which is modeled after the Roman square capitals), even in the same document that is meant to have harmonized designs for both. The Arabic script, for example, is _inherently_ more cursive than Hebrew. Similarly, Greek letters are inherently more cursive than Latin letters. So Greek text would call for "tails", whereas the micro sign would need a more romanized appearance because it is strictly used in a Latin context.

Perhaps it can also be a ligature, as it seems that the Greek letter mu can (or even should) be used in the micro sign's place.
