### ISSUE TITLE
Variant for colon aligned with equal sign

### ISSUE THREAD

**Issue by xsrvmy** [be5invis/Iosevka#1272]
- [X] The requested variant shape does not go too far away from Iosevka's design.
- [X] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [ ] At least two monospace/programming fonts, created by different designers, supported the requested variant. Provide images below.

------

*Please provide your justification here.*
Is it possible to provide a variant that makes the colon aligned with the equal sign, for use with terminals that do not support ligatures? `:=` looks pretty bad in that case.

**Comment by be5invis** [comment]
`:` is punctuation so it should follow punctuation metrics (i.e., align with `,`, `.`, `;`, etc). Making it align with `=` is something a ligation should do.
Mark as Needs Justification.

**Comment by galdor** [comment]
Aligning `:` and `=` is visually important in programming languages with a `:=` operator such as Go.

In the current state, `:=` is ugly because the equals character is not vertically aligned with the two dots of the colon character.

PragmataPro, Berkeley Mono, MonoLisa, Triplicate A Code, all these fonts do it correctly.

An alternative for the `=` character would be helpful, not everyone is using ligations.
