### ISSUE TITLE
The 14pt font display ( -, =)  Error in the intellij idea

### ISSUE THREAD

**Issue by deae** [be5invis/Iosevka#13]
the 12pt display right, but the 14pt display wrong, please see the attached pic.
![ios-01](https://cloud.githubusercontent.com/assets/11693619/9724288/6053ea5e-5607-11e5-9819-a10fc9501ac9.png)
![ios-02](https://cloud.githubusercontent.com/assets/11693619/9724289/66801e52-5607-11e5-8cc2-4cd65df07bf8.png)
![ios-03](https://cloud.githubusercontent.com/assets/11693619/9724292/69c11c6a-5607-11e5-859d-61c4cc307804.png)

**Comment by be5invis** [comment]
Maybe gridfit related.

**Comment by deae** [comment]
v0.1.11 the "=" looks good, but the '-' still display wrong.

**Comment by be5invis** [comment]
@deae I cannot figure out why this happens. Fontforge and ftview does not show anything wrong under 14ppem. Maybe it is a Java-specific problem.

**Comment by Zhichao-Hong** [comment]
IntelliJ is pure Java application and font rendering especially on osx has been a big issue since Apple no longer contributes to build the JVM.  JetBrain has even recently forked their own JVM just to fix the font rendering issue.  However, it is still far from perfect.  Actually I found Iosevka rendering much better than other fixed width fonts.  Great job here for this great font!

**Comment by deae** [comment]
good news, the version 1.5.1, the font display correct. I use the "withfw-iosevka-1.5.1".

**Comment by deae** [comment]
![qq 20151224124646](https://cloud.githubusercontent.com/assets/11693619/11989661/71f46926-aa3c-11e5-8280-0b3cc1bf733d.png)

**Comment by be5invis** [comment]
@deae Hmmm maybe some weird internal data changes fixes this issue. Closed.
