### ISSUE TITLE
About Stable Release

### ISSUE THREAD

**Issue by GulajavaMinistudio** [be5invis/Iosevka#1335]
I see Iosevka now more and more stable and have complete features. I think Iosevka should focus on release minor bug fix version, instead create new major version. And maybe should focusing on online builder tools [Iosevka Customizer](https://typeof.net/Iosevka/customizer), 
so some user can make custom iosevka font in the web without compiling itself on their local computer.

What do you think ?

**Comment by be5invis** [comment]
Becoming "stable" is purely because I don't have a lot of bandwidth recently.

The version number mostly follows _semver_: when any breaking changes are made, the major version will increase.

Creating an on-web compiler is possible but needs a lot of work (like, creating a WebAssembly version of TTFAutohint). Such a building process also takes a lot of time. (On my machine, it takes about 5 minutes per instance without caches. I use a 32-core CPU to make the build time "tolerable".)
