### ISSUE TITLE
No arrow matches box drawing horizontal line

### ISSUE THREAD

**Issue by p00f** [be5invis/Iosevka#1398]
None of the arrows are aligned with box drawing horizontal line (`u+2500`)
Black left/right-pointing pointers (`u+25ba/25c4`) as suggested [here](https://stackoverflow.com/questions/40897069/is-there-an-ascii-arrow-that-will-fit-seamlessly-with-the-box-drawing-characters)
![image](https://user-images.githubusercontent.com/36493671/184474308-2cc60385-631e-431d-8e5a-8f122948eb1a.png)
Normal arrows (`u+2190/2192`) as suggested [here](https://github.com/be5invis/Iosevka/issues/374#issuecomment-549134071)

![image](https://user-images.githubusercontent.com/36493671/184474473-b614c81a-0fba-4b08-b810-14338afb0a78.png)

---

* Your font version: 15.6.3 (`ttc-iosevka 15.6.3-1` from archlinux)
* Your font variant: Normal
* Your operating system (name and version): archlinux
* Your application using Iosevka: kitty

If you have problem when building Iosevka, please provide these information: N/A

**Comment by p00f** [comment]
JetBrains Mono and Monaco's normal arrows are aligned and their black pointers are almost aligned

**Comment by p00f** [comment]
nvm this worked in another terminal

**Comment by be5invis** [comment]
In the font file arrows and box-drawing symbols actually align _very well_: their centerline's y-positions' difference is 2/1000 em!
I suspect your terminal is doing something special to the box-drawing characters, making them misaligned with arrows. Perhaps you need to file a bug to Kitty.

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/184480063-ec4bbdfe-10ae-4ceb-9130-9723747deb1a.png)
This is Iosevka Term. It looks like Kitty shrinks your arrows and triangles, perhaps you are using the "normal" Iosevka instead of Iosevka Term. The normal Iosevka have arrows that are 2-cell wide, so Kitty will shrink them (since arrows are 1-cell wide in WCWIDTH). Arrows in Iosevka Term are narrow, so it should behave correctly in Kitty.

**Comment by p00f** [comment]
Yep Iosevka term is fine, thanks
