### ISSUE TITLE
Consolidation of Glyph Variants Requests

### ISSUE THREAD

**Issue by be5invis** [be5invis/Iosevka#140]
- [x] Clearify `#`
- [x] More curly `{}`
- [x] Sulzbacher Form `ß`
- [X] `@` in four-fold
- [X] `@` like that in Fira
- [x] “Hooky” `t`
- [x] Percentage with rings (%)
- [ ] Ampersand (`&`) with open contour
- [x] Variants for `1`
- [ ] Square puncatuation dots : `.`, `,`, `:`, `;`, `?`, `!` and quotes
  - Do we need to break into two selectors? one for `.` and one for `,`?
- [x] Straight/curly `y`
- [ ] Rounded box-drawings (maybe a non-OT selector)
- [ ] Small caps by default (with `c2sc` feature?)
- [ ] Flat tail `t` / Angular `t`
- [x] Force-serif `7`

**Comment by p-e-w** [comment]
Thumbs up for modifying `{}` – their curvature too closely resembles `()` and at small sizes they are hard to distinguish. [Input Mono](http://input.fontbureau.com/) is an example of a font that leaves no doubt which type of brackets is which.

**Comment by be5invis** [comment]
So, @p-e-w, do you like this?

![image](https://cloud.githubusercontent.com/assets/240091/21961897/e7150080-db50-11e6-84f3-303b0ecb2bae.png)

**Comment by sliceofcode** [comment]
@p-e-w I agree. I don't like the close resemblance to `(`.
@be5invis Very nice!

**Comment by be5invis** [comment]
@p-e-w @sliceofcode Hmmm...

![image](https://cloud.githubusercontent.com/assets/240091/21964541/a7eccc3e-db88-11e6-9753-c21dc475c278.png)

**Comment by sliceofcode** [comment]
@be5invis That looks nice. Although I prefer the tip of the brace (I don't know what it is called) to extend more instead of being short, like in Monaco:

![20170115_102407_dyg](https://cloud.githubusercontent.com/assets/4206232/21965056/c734598a-db0c-11e6-9334-1123a82b32bf.png)

That's just my personal preference though, the font looks great :smile: If you don't mind me asking what colorscheme and text editor is that? Looks great with Iosevka!

**Comment by be5invis** [comment]
@sliceofcode VSCode, theme is Railgun

**Comment by sliceofcode** [comment]
Alright, thanks.

**Comment by p-e-w** [comment]
@be5invis: Sorry for the late reply. I have studied the changes and find two small issues: First, the new `ß` is hard to distinguish from `B` because the bottom loop almost touches the stem. Other fonts eschew this problem by either leaving more space between the loop and the stem or by making the two loops "wavy" in a fashion that is obviously different from `B`. I would recommend the first approach as I think the overall glyph shape is good already.

Second, I agree with @sliceofcode in that I feel all three bracket types should be wider than they currently are, and indeed I believe should be as wide (and as tall) as the character cell allows. While your adjustments make `(` and `{` more distinct, `{` almost looks like `|` now because of its small horizontal extent. I love the Monaco example given above – the wide extent makes it possible to really flesh out the different shapes, and matches the role brackets usually have in code: Containers for code blocks or array-type objects, which should be immediately recognizable.

In any case, I continue to be amazed by your responsiveness and swift release cycle. I am not aware of any other font with a development speed approaching that of Iosevka.

**Comment by sliceofcode** [comment]
Here is another comparison. This time, Iosevka and Input.
![2017-01-21-10 27 44](https://cloud.githubusercontent.com/assets/4206232/22176659/44ac0e74-dfc4-11e6-951a-79d3ea26c2f0.png)
Input's braces are shorter, and "longer". You can clearly see the difference between `|`, `()`, and `{}`. Although the same can be said for Iosevka, I prefer Monaco/Input style braces.

I agree on what @p-e-w said, especially the last sentence. It's what makes Iosevka so great. :+1:

**Comment by be5invis** [comment]
@sliceofcode well its “wider”.
Given that Iosevka is designed to be **very narrow** (in fact it is the narrowest monospace typeface I know), I think I can increase the width of brackets only a little.

**Comment by be5invis** [comment]
![image](https://cloud.githubusercontent.com/assets/240091/22184352/f35d4d1a-e10a-11e6-9573-4636f3378e65.png)
@p-e-w @sliceofcode Like this?

**Comment by sliceofcode** [comment]
@be5invis Looks like it. :smile: I'll test it out and provide some feedback, if you don't mind.

**Comment by be5invis** [comment]
@sliceofcode It's in Master. build it (on linux please, because OSX fontforge is some sort broken)

**Comment by be5invis** [comment]
Add some overshoot
![image](https://cloud.githubusercontent.com/assets/240091/22185145/28889b74-e11b-11e6-98c5-f3e8b019f2be.png)

![image](https://cloud.githubusercontent.com/assets/240091/22185148/3b3d820c-e11b-11e6-9523-ca490ea43745.png)

**Comment by sliceofcode** [comment]
![2017-01-22-11 44 53](https://cloud.githubusercontent.com/assets/4206232/22185322/4692c2d0-e098-11e6-861e-d8a1829d1178.png)

@be5invis Looks beautiful. :smile:

Had to use this workaround for Fontforge to work properly in Linux: fontforge/fontforge#2992

**Comment by be5invis** [comment]
@sliceofcode I have no clue what happened to FF. Perhaps I should write something to get rid of it (for example, `otfcc-ttcize` is written to replace FontForge's TTC exporter)... It's annoying, really.

**Comment by sliceofcode** [comment]
![2017-01-22-11 52 03](https://cloud.githubusercontent.com/assets/4206232/22185378/3c2ac8fa-e099-11e6-8876-ab2fba70ebb9.png)

Here is another preview, this time all weights. Click for higher resolution.

**Comment by p-e-w** [comment]
Interesting... in @sliceofcode's last preview, for the light weights `}` is shifted upwards compared to `[`, while for the heavy weights it is shifted very slightly downwards (or perfectly aligned, can't decide which one). Is the overshoot weight-dependent?

Otherwise, this is an enormous improvement, @be5invis! I'm also excited about the possibility you hinted at of eliminating FontForge from the build chain, which has always felt like the odd one here (FF is primarily a GUI tool, after all). A pure command line-based font compilation toolchain could literally usher in a new era of "precision fontmaking", of which Iosevka thus far appears to be the only example.

**Comment by be5invis** [comment]
@p-e-w `{}` and `[]` are perfectly vertically middle-aligned. His image just does not have enough resolution. FF is a cluster of uncertainty and bugs. It should be eliminated.

**Comment by jdw1996** [comment]
I'm glad that the `#` sign has been mentioned—that is the least clear symbol in the font for me. However, there are a couple others that I would also love to see variants of:
* `$` — Right now, I find that the dollar sign looks a bit too much like an `S`. It would be nice to have a variant that created a stronger distinction. Here are some examples; from left to right, the fonts are Iosevka, Monoid, Input, and Consolas:
![dollars](https://cloud.githubusercontent.com/assets/17225098/23289978/7fe4390a-fa1b-11e6-82f6-a702194fe222.png)
While I prefer the `$`s in Input and Consolas to Monoid's, something more similar to Monoid's `$` may be more feasible because Iosevka is such a narrow font.
* `Q` — The current letter `Q` is nice and simple, but I find it a bit hard to distinguish from `O`. Again, I think there are a few different ways to handle this; from left to right this image shows Iosevka, Monoid, Input, and TexGyre Schola:
![q](https://cloud.githubusercontent.com/assets/17225098/23289933/330b3e58-fa1b-11e6-88fc-5e01eb00960f.png)
Input's `Q` is the most similar to the current Iosevka `Q`, but its tail is more pronounced, making it easier to see. That said, I think the other two are clearer, as the tail breaks the circular outline of the letter.

Thanks again for the great font!

**Comment by be5invis** [comment]
@jdw1996 
How about this?

![image](https://cloud.githubusercontent.com/assets/240091/24495621/5b7309a8-1568-11e7-85ad-49126811a37d.png)

**Comment by be5invis** [comment]
@therockmandolinist 
Here you are:

![image](https://cloud.githubusercontent.com/assets/240091/24496845/0f0eb540-156c-11e7-8472-45c0ab35fd49.png)

**Comment by be5invis** [comment]
@jdw1996 And we have this:

![image](https://cloud.githubusercontent.com/assets/240091/24501052/7f18df06-157a-11e7-9aab-5fff7f2d0ea4.png)

**Comment by be5invis** [comment]
@nick-s-b
This is for you:

![image](https://cloud.githubusercontent.com/assets/240091/24501980/5d9d8a1c-157e-11e7-95c1-4e11c85cf2b0.png)

**Comment by therockmandolinist** [comment]
@be5invis thanks, but I believe that's closer to z-shaped - wouldn't hooky be straight down?

Also perhaps for future consideration, I had mentioned the possibility of a t with more similar curvature to the l. You can see the difference here:
![2017-03-30_09 49 52](https://cloud.githubusercontent.com/assets/9020453/24507399/55d2fa4c-152e-11e7-9927-56c67fc38ed0.png)

**Comment by nick-s-b** [comment]
@be5invis thank you! Looks great and much better than the current one.

**Comment by jdw1996** [comment]
@be5invis The `Q`, `$`, and `#` all look awesome!

**Comment by be5invis** [comment]
@therockmandolinist So you need a `t` like it is in Futura?

**Comment by therockmandolinist** [comment]
@be5invis that's the type I was referring to, yes. I wouldn't say _need_, it was a suggestion for consistency :)

**Comment by be5invis** [comment]
@therockmandolinist 

![image](https://cloud.githubusercontent.com/assets/240091/24536878/51c26298-1610-11e7-80f9-b03689f90a80.png)

**Comment by therockmandolinist** [comment]
@be5invis quite so! very nice

**Comment by nick-s-b** [comment]
@be5invis I'm still hung up on hash/octothorpe... lol. After compiling and looking at the latest one, I still wish there was a slanted variation. Slanted one is the default in Monospace (which is probably the default monospace font for all distros) and it's also default one in Pragmata Pro and slew of other "programmer fonts". Even Roboto and other regular screen fonts have it slanted. So when you read some code in a browser, it will most certainly have a slanted #. it's weird when I go to Terminal and then see it straight up & down.

Here's a slanted one in Monospace at 10pt in the Terminal:

![https://i.imgur.com/rrdwxhU.jpg](https://i.imgur.com/rrdwxhU.jpg)

and here's the outline of Pragmata Pro's in FontForge:

![https://i.imgur.com/mnrVuym.jpg](https://i.imgur.com/mnrVuym.jpg)

I really hate bugging you but if you get a chance, could you please add a slanted variant?

Thanks :)

**Comment by be5invis** [comment]
@nick-s-b 
My pleasure.

![image](https://cloud.githubusercontent.com/assets/240091/24561059/ec5a2676-1677-11e7-9378-442e27294a04.png)
![image](https://cloud.githubusercontent.com/assets/240091/24561067/f4be85aa-1677-11e7-8ad6-00e71754bf0f.png)

**Comment by nick-s-b** [comment]
@be5invis wow! Thank you! Looks great!

**Comment by AndydeCleyre** [comment]
I'd love to see some options to further differentiate within each of the following pairs (so an alternate of at least one from each pair):

- `db`
- `qp`
- `un`

This can be especially helpful for those with dyslexia. Below are samples from other fonts, under Iosevka; but I don't know what might work best with your style. Maybe `d-hooky`, `b-hooky` . . .

![dbqpun](https://user-images.githubusercontent.com/1787385/27064989-66f3c336-4fc8-11e7-9999-c77ca0f1294b.png)

**Comment by jdw1996** [comment]
@AndydeCleyre Any chance you could post a list of the fonts you've shown here?

**Comment by AndydeCleyre** [comment]
@jdw1996 

![image](https://user-images.githubusercontent.com/1787385/27066898-6164239a-4fd5-11e7-89d7-3dc8fe194cf1.png)

**Comment by be5invis** [comment]
@AndydeCleyre Have you tried Iosevka Slab?
The general design of Iosevka is neo-grotesque so `d` and `b` **should** be similar.

**Comment by AndydeCleyre** [comment]
@be5invis Yes, but I find the regular style more readable and less distracting. I'm unfamiliar with neo-grotesque standards; I'll read what I can find.

**Comment by AndydeCleyre** [comment]
@be5invis fwiw I found a couple of fonts described as neo-grotesque that firmly disambiguate `d` and `b`, and `q` and `p`: 

[Safety](https://playtype.com/font/safety)

![image](https://user-images.githubusercontent.com/1787385/27094427-04f62604-5038-11e7-8b63-181eee94f3b7.png)

[Berlingske Sans](https://playtype.com/font/berlingske-sans)

![image](https://user-images.githubusercontent.com/1787385/27094525-4f1ca622-5038-11e7-9286-d7559c796af0.png)

Meanwhile, I'm compiling a slab variant to reconsider it.

**Comment by jdw1996** [comment]
I really like the curlier italic `y` in the slab version of Iosevka, but I prefer to use the sans version.  Is there any way you could add the option of a curlier `y` to the sans?

**Comment by alexeyten** [comment]
I would like to request square variant for period (like one in Cousine)
![image](https://user-images.githubusercontent.com/44377/32364003-65817134-c083-11e7-9c51-adbfddbd5aac.png)

**Comment by be5invis** [comment]
@alexeyten 
Looks interesting but might be hard to implement. Symbols that would be affected:
 - `i`, `j`, etc. — Mark dots
 - `.`, `:`, `?`, `!`, etc. — Periods
 - `,`, `;`, `“`, `”`, etc. — Commas

**Comment by notsukamto** [comment]
Can you also add variation for f straight and curly? I would like to have an f-straight for my italic.

**Comment by be5invis** [comment]
@notsukamto @jdw1996 @moosotc  Added in 1.14.2

**Comment by moosotc** [comment]
I was told that /(002F / SOLIDUS) in Iosevka is too tall never bothered me right until the moment i was told that it is.. Now i can help but notice that it is indeed too tall.. A shorter variant would be nice to have.

**Comment by AmerM137** [comment]
I changed the "hook" parameter and the shape of "t" is now perfect for me! (closed issue #269). Just out of curiosity do we still have to officially request a variant for t? I am just making sure I understood your comment to my question correctly.

-Amer

**Comment by AndydeCleyre** [comment]
@AmerM137 Can you share a screenshot and the hook value?

**Comment by AmerM137** [comment]
Hook = 50
![iosevka hook50](https://user-images.githubusercontent.com/37887075/39958563-5bbd7850-55ca-11e8-8163-3bfc942e35fe.PNG)

**Comment by AmerM137** [comment]
After trying the modified code with hook=50 I did notice that the "f", "c", and probably some other letters had their hook shortened also which changed their shape. I think the originals look better.

Is there a way you can add a parameter just for the "t"? This way we can change "t' and leave the other letters intact. Maybe a "thook" just like we have "ahook", "shook" etc?

**Comment by AndydeCleyre** [comment]
I'd like to see another `$` variant, as I still find both options uncomfortably close to plain old `S`. I don't know what would be better, though.

Some notes from other fonts' choices:
- I don't like a slanted line, because that looks like a "crossed out" `S`
- Monoid's version is pretty good, though unusual
- Everson Mono uses a longer bottom stem, which may be slightly better
- a double-line (like Coustard) is very normal and may be an improvement
- some put slight curves on the line (like Laila), but those are curvier fonts altogether
- some use a very different `S` shape (like OCRA, Offside, Snippet, Song Myung)
- simply greater line-to-`S` ratio may be an improvement (like Sacramento, Vibur)

Those were all the strategies I noticed, maybe someone else knows of others, or has a great idea.

After considering the above, my suggestion at this point would be a variant with open contour, two longer lines, a smaller `S` component, and a higher placement for that `S` component, making the bottom lines longer than the top.

![image](https://user-images.githubusercontent.com/1787385/40187688-1bf8fa28-59c6-11e8-94a5-2f300e2514a6.png)

**Comment by AndydeCleyre** [comment]
Another idea for a more distinguished `$`: cut out a centered vertical stripe

![dollar_sign_iosevka_split](https://user-images.githubusercontent.com/1787385/45243391-a0bd6880-b2c1-11e8-960b-1d485be85703.png)

This is inspired by many fonts' Euro, even though that's a two-stripe symbol:

![screenshot_201809 7_171347](https://user-images.githubusercontent.com/1787385/45243408-afa41b00-b2c1-11e8-99a5-25cd7a7bbb1f.png)

**Comment by lshoravi** [comment]
I'd love a c with a overhang: 

![image](https://user-images.githubusercontent.com/42211142/46400191-1c140d80-c6fa-11e8-875c-389bcf00636b.png)

**Comment by AndydeCleyre** [comment]
Here's a mockup of another `&`, based on `U+01B8 (Latin capital letter ezh reversed)`. It would maybe make more sense to base it on a rounder character, like `U+0190 (Latin capital letter open E)`. Just trying to reinvigorate `&` discussion.

![iosevka_ampersand](https://user-images.githubusercontent.com/1787385/47606259-73e32300-d9df-11e8-96f5-f8939cef3d16.png)

**Comment by flying-sheep** [comment]
OK, this definitely needs to be pinned to make @stale stay away.

**Comment by flying-sheep** [comment]
hi @be5invis can you please reopen and add the `pinned` label?

**Comment by sharpjs** [comment]
I would _love_ a `U+002A * Asterisk` variant that is low *and* six-pointed, as in Menlo.

<img width="195" alt="menloasterisk" src="https://user-images.githubusercontent.com/708461/53685603-c2783500-3cd1-11e9-8875-e04210b60bd4.png">

I asked in #81 , but this issue seems a more appropriate place to ask.

**Comment by sharpjs** [comment]
Just found the Patreon link and became a patron.  I hereby also pledge **one-time bounties**:
* `USD $100` for the Menlo-style asterisk as mentioned above.
* `USD $ 30` for "percentage with rings" as mentioned in the initial post of this issue.

**Comment by be5invis** [comment]
@sharpjs 
(It will be on `cv61`)
![image](https://user-images.githubusercontent.com/240091/53932906-05257d00-40d7-11e9-91c4-4d546e910748.png)

**Comment by be5invis** [comment]
@sharpjs 
![image](https://user-images.githubusercontent.com/240091/53934823-1f635900-40df-11e9-8fc2-3d025a6d8490.png)
![image](https://user-images.githubusercontent.com/240091/53934820-1a9ea500-40df-11e9-83f5-f57b9255292f.png)
God, I love this.

**Comment by lshoravi** [comment]
That's fantastic. Great job!

**Comment by be5invis** [comment]
@sharpjs @eproxus 
![image](https://user-images.githubusercontent.com/240091/53936644-85eb7580-40e5-11e9-9612-8ec50285b543.png)
![image](https://user-images.githubusercontent.com/240091/53936655-8c79ed00-40e5-11e9-80d6-70845e7398be.png)
![image](https://user-images.githubusercontent.com/240091/53936663-94399180-40e5-11e9-9eb7-013f5011ba31.png)
I love this. I will make it default!

**Comment by sharpjs** [comment]
@be5invis 👍 Yep, like that!  Maybe just sliiightly larger, if I may ask.  Either way, I love it.

**Comment by AndydeCleyre** [comment]
Wow, the new `%` is beautiful and striking! What are those `0/00` `0/000` symbols?

**Comment by lshoravi** [comment]
@AndydeCleyre Permille, I believe

**Comment by Markus00000** [comment]
While the new percent sign looks nice and unique, I would rather not have it as a default:

* The split line makes it look significantly different to common percent signs. At first I was confused because I did not read it as a percent sign. Instead, I saw a person waving with their arm (top row: circle is the head, line is the arm). It did not make much sense as the person waving back (bottom row) was upside down. Even now that I know it is supposed to be a percent sign, I cannot unsee those happily waving persons.
* The split line breaks the connection to fractions, which are often denoted by `/`.
* The split line separates the percent sign from the per mille and per ten thousand signs, even though the concept behind all three is identical.

Just my 2%.

**Comment by memophen** [comment]
Odd that I discovered Iosevka just recently, while looking for a holy mono grail for so long. Interesting for its collection of glyphs and variants, as well as for the way the whole thing is produced. As a newcomer, I might say things now that have been said before, but I found little evidence of it so far. Despite all appreciations of the glyphs, I cannot imagine that many people are really happy with the paperclip shapes of the @ sign (cv31 and cv32). At least, I am not.

I've tried to find out the logic of the chosen measures. There is an x-height of course, and a cap height. And -- forgive me not knowing the proper typographical terms -- a somewhat bigger #-height, and an even exceeding slash height. Ascenders don't surpass the cap height, and descenders go slightly deeper than the slash height characters.

Making special characters like # just a bit outstanding from capitals is a defensible design decision in my opinion. But I wonder why cv31 and cv32 were stretched to slash height. Why not #-height, like cv33? That would make these characters less distracting. And I think there is still some room for widening all @ variants a tiny bit.

The slash height in itself doesn't make me enthousiastic either. May I suggest adding an option for a little more modesty by equalizing the top side with the top level of the #-height? That's a more balanced compromise between the combination with uppercase/digits vs the combination with lowercase text. Satisfying everyone (high-levelers vs low-levelers) would require this to be parameterized categorically, I guess. No idea how much effort would be involved in constructing a tweaking mechanism for that.

The attached graphic shows my fiddling around with ss09 based on these ideas, concluded by the same text in PragmataPro.
![Iosevka-at-sign-1-45perc](https://user-images.githubusercontent.com/4470470/54495073-e302da80-48e0-11e9-8174-78ff8cbd1372.png)

**Comment by be5invis** [comment]
To be honest I think some operators are too tall too. I may change the default parameter rather providing a variant.
Parens and brackets won’t be changed. They should be tall to be coupled with other letters, both uppercase and lowercase.

________________________________
发件人: Memophenon <notifications@github.com>
发送时间: Monday, March 18, 2019 1:24:34 AM
收件人: be5invis/Iosevka
抄送: Belleve Invis; Mention
主题: Re: [be5invis/Iosevka] Consolidation of Glyph Variants Requests (#140)


Odd that I discovered Iosevka just recently, while looking for a holy mono grail for so long. Interesting for its collection of glyphs and variants, as well as for the way the whole thing is produced. As a newcomer, I might say things now that have been said before, but I found little evidence of it so far. Despite all appreciations of the glyphs, I cannot imagine that many people are really happy with the paperclip shapes of the @ sign (cv31 and cv32). At least, I am not.

I've tried to find out the logic of the chosen measures. There is an x-height of course, and a cap height. And -- forgive me not knowing the proper typographical terms -- a somewhat bigger #-height, and an even exceeding slash height. Ascenders don't surpass the cap height, and descenders go slightly deeper than the slash height characters.

Making special characters like # just a bit outstanding from capitals is a defensible design decision in my opinion. But I wonder why cv31 and cv32 were stretched to slash height. Why not #-height, like cv33? That would make these characters less distracting. And I think there is still some room for widening all @ variants a tiny bit.

The slash height in itself doesn't make me enthousiastic either. May I suggest adding an option for a little more modesty by equalizing the top side with the top level of the #-height? That's a more balanced compromise between the combination with uppercase/digits vs the combination with lowercase text. Satisfying everyone (high-levelers vs low-levelers) would require this to be parameterized categorically, I guess. No idea how much effort would be involved in constructing a tweaking mechanism for that.

The attached graphic shows my fiddling around with ss09 based on these ideas, concluded by the same text in PragmataPro.
[Iosevka-at-sign-1-45perc]<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F4470470%2F54495073-e302da80-48e0-11e9-8174-78ff8cbd1372.png&data=02%7C01%7C%7C451f703ea5554db699e508d6aafd6d4b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636884402765770042&sdata=jlcCjDATejtUhZp7RoW0GQasUvDXtcPe69Rl%2B8EjC84%3D&reserved=0>

―

**Comment by bluz71** [comment]
Thank you @be5invis and @sharpjs,

I really like the new ringed `%` and six-pointed `*` glyphs. A **big** improvement.

@memophen 
> I cannot imagine that many people are really happy with the paperclip shapes of the @ sign 

I also dislike the paperclip `@`, but it is not the default, the short Fira style is the default and I think that version looks superb. I appreciate that @be5invis has given this font flourishes, such as the short `@` and ringed `%`, it makes looking at code enjoyable.

**Comment by memophen** [comment]
Don't understand me wrong, I really do support the principle of the higher braces etc., and only slightly disagree over how far to go with it. As the current proportions are somewhat peculiar but not distracting, no further insisting is to be expected from my side. Another matter bothers me more: the readability of the digits, especially the nine and the zero.

The change of style between six and nine is not just esthetically unsatisfactory. I imagine the shape of the six was chosen to contrast with the letter G. But even without the existence of G, the open form would be a better choice, since it also contrasts better with the eight. So I would highly appreciate a nine that's a 180 degree rotation of the current six.

If I had to characterize the circular glyphs of Iosevka, I would call them racecourse-shaped. This qualification is applicable to the letter O, the current zeroes, but also to C, G, U, and the current nine. Opposed to that are the oval-shaped characters. There aren't many in Iosevka, but I've found the lowercase theta. Wouldn't that shape (a bit more stretched to the same width as the current letter O) be a better representation of the zero, even more in combination with the current six and the alternate nine I pled for? This would make larger numbers far more readable, in my perception.

Below I tried to make these ideas visible. First a sample sheet of possible letter and digit shapes with or without different zero marks: 
![O0](https://user-images.githubusercontent.com/4470470/54838542-25edf500-4cc9-11e9-849f-193ac7ad3674.png)
Then a lot of solutions for the zero (first line), a sample with the current nine (second line) and a sample with an alternate nine (third line):
![Zeroes](https://user-images.githubusercontent.com/4470470/54838698-8715c880-4cc9-11e9-9b35-911a0a095f15.png)
Would oval-shaped zeroes be problematic? It doesn't look like. The theta does not misbehave at smaller sizes:
![Digits-with-theta](https://user-images.githubusercontent.com/4470470/54838717-95fc7b00-4cc9-11e9-8305-682c0efc880f.png)
As far as I'm concerned, I would be quite happy to see the three current zeroes cv20/cv21/cv22 simply replaced by three equivalent oval ones. However, if people are devoted to the racecourse shapes, addition of the ovals to the assortment of zeroes would be okay as well. The exact kind of slash or dottish thing is less important to me, although my personal preference is the last sequence 1068092 in the second sample (and I'm considering to choose cv51 instead of cv50, but that's a private affair).

**Comment by bluz71** [comment]
> As far as I'm concerned, I would be quite happy to see the three current zeroes cv20/cv21/cv22 **simply replaced** by three equivalent oval ones.

Absolutely **NOT!**

The existing current zeros looks far nicer than the proposed oval zeros (to my eyes). I strongly disagree on changing it.

Your arguments about `9` do make sense, but I am agnostic on that. I like the current `9`, but a change to an inverted `6` would not bother me either.

My 2c as a big fan of the current font.

**Comment by be5invis** [comment]
@memophen Changing the shape of `0` will severely de-harmonize the design consistency between digits and letters. Theta is the only exception case since its upper-case and lower-case are very closely shaped so I have to made some difference.

**Comment by memophen** [comment]
**@be5invis** -- Do we need and want such a fargoing design consistency? Arabic digits are a different species, after all. That was clear when they arrived in Europe (in 976 or just before):
![976-33pct](https://user-images.githubusercontent.com/4470470/54883162-130f2800-4e63-11e9-82c0-a49f627324c4.png)
> (Item de figuris arithmetice: _Scire debemus in Indos subtilissimum ingenium habere et ceteras gentes eis in arithmetica et geometria et ceteris liberalibus disciplinis concedere. Et hoc manifestum est in novem figuris, quibus designant unumquemque gradum cuiuslibet gradus. Quarum hec sunt forma: 9 8 7 6 5 4 3 2 1._)

And it’s also clear in contemporary bookprint, where they still don’t go along the established lines of uppercase and lowercase letters:
![OSF](https://user-images.githubusercontent.com/4470470/54883175-4fdb1f00-4e63-11e9-8460-45a36097019a.png)
Even tabular figures don’t conform the lettering conventions, and I must say, I’m glad they aren’t completely harmonized yet:
![Conformity-50pct](https://user-images.githubusercontent.com/4470470/54883177-5e293b00-4e63-11e9-9c7a-fd32150b8112.png)
In my view, the proposed kind of difference does not imply disharmony. But de gustibus non est disputandum. If you are opponent to freer forms and want to force all glyphs in the same grid, well, it’s your show. Then my best contribution would be advising you to replace the de-harmonizing 6 by a rotated 9.

Nevertheless I think Iosevka has a lot of charms. It would suit well for display on posters and covers, when you want to apply an austere style.

**Comment by AlsoScratch** [comment]
@be5invis You still haven't added my suggestion for the digit 7 having a downward pointing bit.

**Comment by be5invis** [comment]
I already added in the latest dev commit.

________________________________
发件人: AlsoScratch <notifications@github.com>
发送时间: Saturday, August 31, 2019 8:26:57 PM
收件人: be5invis/Iosevka <Iosevka@noreply.github.com>
抄送: Belleve Invis <be5invis@outlook.com>; Mention <mention@noreply.github.com>
主题: Re: [be5invis/Iosevka] Consolidation of Glyph Variants Requests (#140)


@be5invis<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbe5invis&data=02%7C01%7C%7Cf597a51b6cbb4752778908d72e8c3ebe%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637029052187312631&sdata=IK5IyqSJoqyxzQb13%2FabWkAIIVW5W5RtOsyLaeZdjw8%3D&reserved=0> You still haven't added my suggestion for the digit 7 having a downward pointing bit.

―

**Comment by AlsoScratch** [comment]
Where do I find it?

**Comment by AlsoScratch** [comment]
Maybe consider adding it to the task list?

**Comment by be5invis** [comment]
@AlsoScratch https://github.com/be5invis/Iosevka/commit/b789f17c320906a555a0693e5ee52d11ad58b711

**Comment by rileyinman** [comment]
I'd like to request forms of `7` and `z` with the "crossed" style seen in some European countries. The strikethrough makes it easier to distinguish in my opinion and would (hopefully) be simple enough additions.

Examples:

**Comment by robertgzr** [comment]
@memophen @bluz71 I just opened a PR with the inverted six glyph for the nine. I've been using this patch for my daily driver font and ended up preferring it over the current nine

![image](https://user-images.githubusercontent.com/3930615/66270909-0cb52c00-e848-11e9-9149-e23e9f03f4b9.png)

**Comment by zyxw59** [comment]
I'd like a version of `i` and `j` that have the tails at the bottom, but not the serif at the top (to match `l` in `cv27`)

**Comment by zyxw59** [comment]
Oh, it looks like these are available as design options (`v-i-tailed` and `v-j-straight`), but not as `cv` options.

**Comment by be5invis** [comment]
@zyxw59 `v-i-tailed` and `v-j-straight` are originally for Aile. I do not test them on monospace.

**Comment by AndydeCleyre** [comment]
If made available, I'd use and appreciate the old style upper case `G`, without that tooth. 

I don't like when letters get very skinny at joins (like how the `b` and `r` have recently thinned more where the curves meet the vertical bar), and I just like the old `G`.

Thanks again for this incredible project.

**Comment by paolobolzoni** [comment]
I'd like a j variant with the round bottom like `v-j-serifed` (`cv58`) and the sans serif top like `v-j-line` (`cv57`). I prefer the rounded shapes with no serif.

I see zyxw59 asked something similar, buy I am not sure if he obtained it or how.

**Comment by paolobolzoni** [comment]
Did you consider an octothorpe variant without the horizontal lines between the vertical bars?

A-la IBM plex mono:
![ibm plex octothorpe ](https://user-images.githubusercontent.com/1133562/73898294-45374600-48cc-11ea-8d3a-57104df5a469.png)

I personally don't _like_ much, but it is really readable.

**Comment by lshoravi** [comment]
In line with the cursive k, would it be possible to get a nice cursive i?

![image](https://user-images.githubusercontent.com/42211142/74655022-e6a37f00-518b-11ea-9a82-52cc308a949a.png)

**Comment by ChiefMikeK** [comment]
> In line with the cursive k, would it be possible to get a cursive i?
> 
> ![image](https://user-images.githubusercontent.com/42211142/74655022-e6a37f00-518b-11ea-9a82-52cc308a949a.png)

Look$ like this U+2139 from George Douros's Symbola.ttf
![Image](https://github.com/ChiefMikeK/feedback/raw/master/img/u%2B2139.png)

**Comment by cata0309** [comment]
My request is a 'U' variant that is like the JetBrains Mono one:
![image](https://user-images.githubusercontent.com/35623921/76161877-2385e480-6140-11ea-872f-dec57999ec31.png)

**Comment by lshoravi** [comment]
I believe this was just added, @cata0309 

Check out ss14 from the latest release candidate

**Comment by be5invis** [comment]
I'd like to close this issue now.
For further character variant requests, please open separate issues.
