### ISSUE TITLE
Braces regular and bold misalignment

### ISSUE THREAD

**Issue by xsrvmy** [be5invis/Iosevka#1422]
The hinting of the braces causes the normal and bold variant to be misaligned. This is at point size 12 without hidpi. Presumably this has something to do with hinting.

![image](https://user-images.githubusercontent.com/7594338/191149084-100be140-3744-4ba2-9616-453a762a0096.png)

---

* Your font version: 16.2.0
* Your font variant: SS12
* Your operating system (name and version): Linux Mint 21
* Your application using Iosevka: Emacs, MATE terminal (VTE)

**Comment by be5invis** [comment]
`ttfautohint`'s "reference font" feature (that unifies blue zones) always fails on my system :(. Maybe a bug in TTFA?

cc. @lemzwerg

**Comment by xsrvmy** [comment]
Hmm... might try calling ttfa myself then since I am compiling a customized version.

**Comment by lemzwerg** [comment]
@be5invis, this is easily possible :-) Please be more specific what problems you encounter, ideally with a test case that I can check.

**Comment by be5invis** [comment]
@lemzwerg 

This command (on win32)

```powershell
ttfautohint -R .\dist\iosevka\ttf\iosevka-regular.ttf .\dist\iosevka\ttf-unhinted\iosevka-bold.ttf .\dist\iosevka\ttf\iosevka-bold.ttf
```

... gives me this error message:

```
An error with code 0x02 occurred while loading the reference font
 unknown file format  
```

Not sure whether it is platform-specific.

Using `ttfautohint 1.8.4`.

**Comment by nyanpasu64** [comment]
Ran into the same bug (`ttfautohint -R/--reference` fails on Windows) and finally found the cause:

https://repo.or.cz/ttfautohint.git/blob/HEAD:/frontend/main.cpp#l1387

`reference = fopen(reference_name, "r");`

The reference font is a binary file and should be opened with "rb", otherwise it will be corrupted on Windows. Making this change fixes my local build of `ttfautohint-1.8.4` on MSYS2 UCRT64.

I don't know if `control = fopen(control_name, "r");` should also be opened with "rb" or not.

I haven't reported upstream to FreeType/Werner Lemberg yet. @lemzwerg you could fix this directly, or I or @be5invis could make a post to freetype-devel@nongnu.org.

**Comment by lemzwerg** [comment]
Thanks a lot!  I've pushed your fix to the `ttfautohint` repository.

**Comment by be5invis** [comment]
@lemzwerg Do you have plan for next release?

**Comment by lemzwerg** [comment]
No plans yet, sorry.
