### ISSUE TITLE
`Zero` assignment for `SS08`

### ISSUE THREAD

**Issue by tywtyw2002** [be5invis/Iosevka#1549]
In Pragmata Pro, the `zero` is reverse-slashed, and Iosevka already had `reverse-slashed-split-oval` `zero`. 
It may change the `SS08` `zero` default assignment from `dotted-oval` to `reverse-slashed-split-oval` to match the original Pragmata Pro.

![font](https://upload.wikimedia.org/wikipedia/commons/f/f8/PragmataPro_sample.png)

**Comment by shytikov** [comment]
Hej! 

You may check [my custom build **Pragmasevka**](https://github.com/shytikov/pragmasevka) where I try to match Iosevka closely as possible to the divine `PragmataPro`.

It corrects many aspects, including, but `zero` is worse than that :( Because Pragmata uses almost hexagonal shape there, there is no matching glyph in `Iosevka` so far.

**Comment by tywtyw2002** [comment]
> my custom build **Pragmasevka**

I will try it, thx.
