### ISSUE TITLE
The "inverse" shapes in Geometric Shapes

### ISSUE THREAD

**Issue by Logo121** [be5invis/Iosevka#1606]
I'm not very sure about this one, but my interpretation of these inverse shapes (25D8-25DB) is that the inverse "background" part should cover the whole character space, like those in the legacy set.

Here's a comparison with other fonts (`◘◙◚◛` and a `🮴` for comparison if supported):
![image](https://user-images.githubusercontent.com/21302803/224882396-99b8e331-74ca-4e3a-994d-5f01070ad440.png)
As far as I've found only unifont, Fairfax HD and Pragmatapro (not pictured) actually handles them like the newer inverse characters.  Others (including Iosevka) wrap the shape with a small black rectangle.  
But the non-terminal version actually has a full width shape but a half-width inversion, which looks wrong to me at least.

A justification for unifying these inverse backgrounds can probably be made by looking at how (two of) these characters looked like from the pre-Unicode usage:
![image](https://upload.wikimedia.org/wikipedia/commons/f/f8/Codepage-437.png)
from [wiki](https://en.wikipedia.org/wiki/Code_page_437).

**Comment by be5invis** [comment]
Let's ask @dscorbett: should U+25D8 ... U+25DB behave like a hollow geometric shape over a inked terminal cell?

**Comment by dscorbett** [comment]
Yes, the original intent was to have a hollow shape on an inked cell. These inverse characters come from old monospace character sets used on terminals with no tracking or leading, where the glyphs joined to adjacent glyphs (left, right, above, or below) without any gaps. The same is true for box drawing characters and shade characters, whose glyphs Iosevka does make joining.

It seems like a lot of modern fonts don’t follow the original intent. If enough of them add gaps around the black rectangles, maybe it isn’t wrong now. I still think it is better to follow the original intent because the glyphs with gaps don’t seem useful for anything.
