### ISSUE TITLE
hyphen, endash: all the same length

### ISSUE THREAD

**Issue by h1mal** [be5invis/Iosevka#164]
* Your font version: 1.11.0
* Your font variant: Term-variants, probably others, too.

* Your operating system (name and version): MacOS X 10.11.6
* Your application using Iosevka: (some Java applications may have problem in showing Iosevka properly. It is a bug in Java's GUI components.): Sublime Text 3, TextMate 2.0, TextWrangler 5.5.2, Visual Studio Code 1.9, Xcode 8.2.1

---

Describe your problem here. Provide pictures and files if necessary.

The characters of the hyphen - U+002D and the enDash – U+2013 have the same length. The enDash should be longer than the hyphen. See https://en.wikipedia.org/wiki/Wikipedia:Hyphens_and_dashes
![iosevkaterm_hyphen_endash](https://cloud.githubusercontent.com/assets/763172/23857580/14a2b766-07fe-11e7-83c4-6c684a8be900.png)
![iosevkaslabterm_hyphen_endash](https://cloud.githubusercontent.com/assets/763172/23857588/1936a42c-07fe-11e7-996d-50e5917cb534.png)

**Comment by be5invis** [comment]
But this is a **monospace**...

**Comment by adnion** [comment]
In other monospace fonts the characters minus `-` and endash `–` are easier to distinguish.
In 'source code pro' both characters have slightly different vertical alignment.
Thank you for iosevka.

**Comment by camjac251** [comment]
Hi, I realise this is an old issue, but I’m encountering the same readability difficulty with Iosevka Term in Windows Terminal.

I strongly prefer Iosevka’s narrow lettering and would like to keep its existing character-cell widths. My question is specifically about **the visible stroke lengths within those cells**, rather than giving the characters different advance widths.

At my normal reading size, the individual hyphen-minus (U+002D), en dash (U+2013), and em dash (U+2014) are difficult to distinguish. This is separate from connected-hyphen ligatures: it also occurs in isolated examples such as `[-]`, `[–]`, and `[—]`. Disabling ligatures therefore does not address that particular distinction.

I also tried ordinary Iosevka instead of Term. Its wider em dash overlapped adjacent characters in my Windows Terminal setup, so changing the terminal’s width policy or using a wider advance is not what I’m proposing.

Would an **optional character variant** be welcome that retains the current advances, vertical alignment, and stroke thickness, but uses a shorter hyphen and an intermediate-length en dash relative to the full-cell em dash? Defaults would remain unchanged.

The current [dash implementation](https://github.com/be5invis/Iosevka/blob/fe27e532e296102a2afb5b27963cf034a50866f7/packages/font-glyphs/src/symbol/punctuation/dashes.ptl) appears to make this distinction possible: the stroke endpoints can be adjusted without increasing the advance width.

JetBrains Mono and IBM Plex Mono are potential reference designs for more differentiated dash proportions. Both also have corresponding [Iosevka stylistic sets](https://github.com/be5invis/Iosevka/blob/fe27e532e296102a2afb5b27963cf034a50866f7/doc/stylistic-sets.md). I can provide matched specimens and a prototype following the [character-variant contribution criteria](https://github.com/be5invis/Iosevka/blob/fe27e532e296102a2afb5b27963cf034a50866f7/.github/ISSUE_TEMPLATE/character-variant-request.md), including checks for related hyphen aliases and ligatures.

Is this a direction you would consider, or would you prefer it remain a private custom build? Happy to open a fresh variant request if that is preferable to continuing this closed issue.
