### ISSUE TITLE
Block Request: Armenian (`U+0530..U+058F`)

### ISSUE THREAD

**Issue by jmcwilliams403** [be5invis/Iosevka#1664]
- The requested character is...
  - [ ] Latin
  - [ ] Cyrillic
  - [ ] Greek
  - [ ] Punctuation
  - [ ] Symbol
- [x] Some other monospace/programming fonts supported this character. Provide images below.

------

The Armenian script is like a long-lost relative of Latin/Greek/Cyrillic, and is often also displayed under a Roman font, as glyphs can be indirectly derived from lookalikes in Latin/Greek/Cyrillic

Example in Consolas:
![image](https://user-images.githubusercontent.com/37010132/231773409-3ec2883e-ec5b-48df-bacf-6aba30317f15.png)
Example in Courier New:
![image](https://user-images.githubusercontent.com/37010132/231773898-0328c472-3bc5-4eab-8a24-d6ceb85e39c1.png)
Example in Julia Mono:
![image](https://user-images.githubusercontent.com/37010132/231774442-3a8f3098-6283-4eb8-b12a-27953aa2644f.png)

**Comment by nkruglikov** [comment]
Many computer scientists moved to Armenia after 2022-02-24. Also, some prominent companies were founded there, like Picsart and Krisp.ai.

My terminal right now (making a data pipeline for my small business). You can see Latin and Cyrillic are rendered fine, while Armenian is sticking out.
![Screenshot 2024-05-10 at 12 12 10](https://github.com/be5invis/Iosevka/assets/8327627/3ca43c6b-3fea-457a-9bd3-cff2f508ec2e)

**Comment by Logo121** [comment]
(leaving this for future reference: https://fonter.am/)

Well, no one here really knows Armenian typography (or how those characters work in Grotesque/Slab Serif style at least), so we can't really do anything about it now.

You can contribute if you want tho

**Comment by Logo121** [comment]
After #2556:
![image](https://github.com/user-attachments/assets/4f959bff-a0fd-4e63-8074-479cc9ec21f8)

Btw @jmcwilliams403 technically this issue is not completed because the combining characters (including some punctuation) and the eternity symbols are not implemented yet

**Comment by Logo121** [comment]
This probably can be closed now thanks to #2567, but just for information, this is what I meant about the case of tonal punctuation/stress marks:

![image](https://github.com/user-attachments/assets/e6301029-453e-4dce-9d99-eb33822b0b55)
![image](https://github.com/user-attachments/assets/e79530d2-e7b8-4adb-8b54-d9bb123fd2b4)
Source: https://r12a.github.io/scripts/armn/hy.html#tonalpunctuation

Not sure how it interacts with regular diacritics though, since (I think) they aren't really used outside of Armenian dialectology.
