### ISSUE TITLE
How to enable a specific type 16 character variant for 'f' in cv31?

### ISSUE THREAD

**Issue by lakshits11** [be5invis/Iosevka#1741]
I want that in cv31, I want to activate type 16 `f`. Is there a specific way to dothat in vscode or on web?

![image](https://github.com/be5invis/Iosevka/assets/54276661/c5f8779f-3f17-4221-9078-37716d1eba66)

**Comment by be5invis** [comment]
```
"editor.fontLigatures": "'cv31' 16"
```

But, well, VSCode UI uses Harfbuzz, but it does not like enabling too many variants all together...

**Comment by lakshits11** [comment]
So there is no other way to enable more than one variant together ??

**Comment by alexeyten** [comment]
Of course there is:
```json
"editor.fontLigatures": "'cv31' 16, 'cv30' 2"
```
![image](https://github.com/be5invis/Iosevka/assets/44377/36fa0715-7a8d-4758-b9a0-dcbe38902286)

**Comment by Alecton4** [comment]
I have the following settings in VSCode:

```json
"editor.fontFamily": "'Iosevka', 'CaskaydiaCove Nerd Font', 'Cascadia Code', 'Sarasa Mono SC', 'Courier New', monospace",
"editor.fontLigatures": "'liga', 'calt', 'ss04'",
"editor.fontVariations": "'cv30' 2, 'cv31' 16",
```

But apparently it's not displaying the variants I want:

![image](https://github.com/be5invis/Iosevka/assets/43232804/14306be8-ec7f-40c0-920c-22b7bdeeb3f7)

![image](https://github.com/be5invis/Iosevka/assets/43232804/a7a50f1c-17f4-4336-93f8-604faee173a4)

![image](https://github.com/be5invis/Iosevka/assets/43232804/cb0ff775-b3fd-4e2b-875a-f48c6aaa4706)

I installed the [super font file](https://github.com/be5invis/Iosevka/releases/download/v27.3.1/super-ttc-iosevka-27.3.1.zip) (sorry I'm not familiar with the font design area and the terminologies) on Linux, and below is my environment:

<details>

Operating System: openSUSE Tumbleweed 20231006
KDE Plasma Version: 5.27.8
KDE Frameworks Version: 5.110.0
Qt Version: 5.15.10
Kernel Version: 6.5.4-1-default (64-bit)
Graphics Platform: X11

</details>

Is it because my settings are problematic or there are issues with VSCode/font?

**Comment by alexeyten** [comment]
> I have the following settings in VSCode:
> 
> ```json
> "editor.fontVariations": "'cv30' 2, 'cv31' 16",
> ```
These should be in `editor.fontLigatures`.

```json
"editor.fontFamily": "'Iosevka', 'CaskaydiaCove Nerd Font', 'Cascadia Code', 'Sarasa Mono SC', 'Courier New', monospace",
"editor.fontLigatures": "'liga', 'calt', 'ss04', 'cv30' 2, 'cv31' 16",
```

**Comment by lakshits11** [comment]
![image](https://github.com/be5invis/Iosevka/assets/54276661/8895d0e6-0d0f-4e1f-a79b-728d0e0e00df)

I want to change bracket styles also but using
```
  "editor.fontLigatures": "'liga', 'calt', 'ss15', 'cv42' 4, 'VSAE' 1",
```
does not change them.

![image](https://github.com/be5invis/Iosevka/assets/54276661/2b26acd8-dee1-4e4b-8833-4e74a71c39b2)
