### ISSUE TITLE
Handling of arbitrary combining accent sequences for Polytonic Greek

### ISSUE THREAD

**Issue by jmcwilliams403** [be5invis/Iosevka#1934]
When attempting to type freestyle polytonic accents using combinations without existing precomposed unicode analogues, the behavior is inconsistent:
```
ἑ͂ἐ͂ Ἑ͂Ἐ͂ ἆἇ ἎἏ
ὁ͂ὀ͂ Ὁ͂Ὀ͂ ἦἧ ἮἯ
Υ̓ Ὑ Υ̓̀ Ὓ Υ̓͂ Ὗ
```
![image](https://github.com/be5invis/Iosevka/assets/37010132/f8b517d6-4dbd-498b-8794-a22bad78027b)
The dotted-circled character behaves fine but is also a novel combining sequence like the other red circled characters.

**Comment by be5invis** [comment]
Your string still has precomposed characters (for example `ἑ͂` is `U+1F11` `U+0342`). For the mark comination we currently only support fully decomposed forms (like for `ἑ͂` is `U+03B5` `U+0314` `U+0342`).
Since no other fonts (I tried Brill and Gentium Plus) support mark combination in these "partial precomposed" strings, resolve as out of scope.
