### ISSUE TITLE
Connected double underline (`U+2017`) and overline (`U+203E`) following connected underline (`_`)

### ISSUE THREAD

**Issue by jmcwilliams403** [be5invis/Iosevka#1947]
- [ ] A programming language requires this ligation. Provide the information below.
- [x] This ligation is implemented in other programming fonts. Provide samples below.

------

This is mainly for Unicode compliance. Whenever Ascii low line joins, these characters should join too.

`__‾‾‗‗`

Consolas:
![image](https://github.com/be5invis/Iosevka/assets/37010132/e0e916e2-5684-4e7b-8813-235a55b3a355)

Liberation Mono:
![image](https://github.com/be5invis/Iosevka/assets/37010132/560e1cc0-e37a-4746-8a45-d153e0be774b)

DejaVu Sans Mono:
![image](https://github.com/be5invis/Iosevka/assets/37010132/be43de37-b2da-4faa-8245-759a6b9960fd)

Lucida Console:
![image](https://github.com/be5invis/Iosevka/assets/37010132/b054dfb5-cf48-4efb-94c7-14fa8ed6456b)

**Comment by be5invis** [comment]
This is a ligation request.
No programming languages are using these (for programming languages that support arbitrary operators, there's no widely-known projects or libraries are using them). Mark as Needs Justification.

**Comment by Logo121** [comment]
A better alternative would be to implement them as *Character Variants*, where we get variants for gapless Under/Overlines vs gapped ones.

Then we get:
![image](https://github.com/be5invis/Iosevka/assets/21302803/dd508bb3-30c6-4da6-91ba-6ea82d467dfc)
![image](https://github.com/be5invis/Iosevka/assets/21302803/1ea7c6ee-fa40-4bd8-88a1-3974df9d27de)
![image](https://github.com/be5invis/Iosevka/assets/21302803/4c837a04-89d6-4c7d-b207-e96114a5ba65)
etc

Note the two rows (two adjacent lines vs lines separated by other characters), which suggests that they are actually not *ligations*, but simply *gapless* glyphs.

Then we can even find non-monospace fonts with this behavior:
* Noto (however, Noto Mono's overline is shorter for some reason) ![image](https://github.com/be5invis/Iosevka/assets/21302803/db996459-280f-4346-8159-73f6a492eacb)
* Nishiki-teki ![image](https://github.com/be5invis/Iosevka/assets/21302803/fc21ac25-f898-4e41-a46b-543df4aa3acf)
* Brill ![image](https://github.com/be5invis/Iosevka/assets/21302803/4b6e6b6c-6170-45e2-855a-d05609f4d792)
etc.

On the other hand, there are a few fonts where none of them connect at all, like FairfaxHD and JuliaMono. But since the gapless variant seems to be more popular, if a new `cv` is not desired than the base glyph can also just be changed to be gapless.
