### ISSUE TITLE
How I can create myself option of Iosevka font?

### ISSUE THREAD

**Issue by Elektroair** [be5invis/Iosevka#2039]
Hello! I have long found Iosevka font and I want to customize myself build, with some changed symbols. I created the idea of it and got code of changes (look it below). When I wanted to create ttf files of my build, I followed the link to [instruction](https://github.com/be5invis/Iosevka/blob/main/doc/custom-build.md), but I didn't understand, how I can make it.

> Note that this repo has a 30+ GB commit history. If you only want the current files and future changes, you can avoid downloading so much by cloning the repo with a [--depth](https://git-scm.com/docs/git-clone#Documentation/git-clone.txt---depthltdepthgt) limit. Example:
> 
> `git clone --depth 1 https://github.com/be5invis/Iosevka.git`

I didn't understand, where I should enter this command. I saw video with entering of this command to some program, but what is it? 

> To build Iosevka you should:
> 
> Ensure that [nodejs](http://nodejs.org/) (≥ 14.0.0) and [ttfautohint](http://www.freetype.org/ttfautohint/) are present, and accessible from PATH.
> Run npm install. This command will install all the NPM dependencies, and will also validate whether external dependencies are present.
> `npm run build -- contents::iosevka`.
> You will find TTFs, as well as WOFF(2) web fonts and one Webfont CSS in the dist/ directory.

I didn't understand, what is `nodejs`, `ttfautohint`, and, finally, where I should to enter command `npm run build -- contents::iosevka`

The instruction is very unclear. I don't understand it totally.

Please help me understand! Thanks a lot!

```
[buildPlans.iosevka-elektroair]
family = "Iosevka Elektroair"
spacing = "normal"
serifs = "sans"
no-cv-ss = false
export-glyph-names = false

[buildPlans.iosevka-elektroair.variants.design]
capital-i = "short-serifed"
capital-j = "serifed-symmetric"
capital-k = "symmetric-connected-serifless"
capital-l = "motion-serifed"
capital-q = "crossing"
capital-s = "serifless"
capital-w = "straight-double-v-serifless"
capital-z = "straight-serifed"
f = "flat-hook-serifless"
g = "single-storey-flat-hook-serifless"
j = "flat-hook-serifed"
k = "symmetric-connected-serifless"
q = "straight-serifless"
r = "compact-serifless"
t = "flat-hook"
w = "straight-double-v-serifless"
y = "cursive-flat-hook-serifless"
z = "curly-serifed"
long-s = "flat-hook-serifless"
eszet = "longs-s-lig-serifless"
capital-gamma = "top-right-serifed"
lower-delta = "flat-top"
lower-iota = "zshaped"
lower-mu = "toothed-serifless"
lower-pi = "tailless"
cyrl-capital-ka = "symmetric-connected-serifless"
cyrl-ka = "symmetric-connected-serifless"
cyrl-capital-u = "cursive-flat-hook-serifless"
cyrl-u = "cursive-flat-hook-serifless"
cyrl-ef = "serifless"
one = "base"
three = "flat-top"
four = "closed"
five = "upright-flat"
six = "closed-contour"
seven = "straight-serifed"
nine = "closed-contour"
diacritic-dot = "round"
punctuation-dot = "round"
tilde = "low"
asterisk = "turn-hex-high"
paren = "flat-arc"
brace = "straight"
guillemet = "straight"
at = "fourfold-tall"
percent = "rings-continuous-slash"
lig-neq = "more-slanted"
lig-equal-chain = "without-notch"
lig-double-arrow-bar = "without-notch"
lig-single-arrow-bar = "without-notch"

[buildPlans.iosevka-elektroair.weights.thin]
shape = 100
menu = 100
css = 100

[buildPlans.iosevka-elektroair.weights.extralight]
shape = 200
menu = 200
css = 200

[buildPlans.iosevka-elektroair.weights.light]
shape = 300
menu = 300
css = 300

[buildPlans.iosevka-elektroair.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.iosevka-elektroair.weights.medium]
shape = 500
menu = 500
css = 500

[buildPlans.iosevka-elektroair.weights.bold]
shape = 700
menu = 700
css = 700

[buildPlans.iosevka-elektroair.weights.heavy]
shape = 900
menu = 900
css = 900

[buildPlans.iosevka-elektroair.widths.normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.iosevka-elektroair.widths.extended]
shape = 600
menu = 7
css = "expanded"

[buildPlans.iosevka-elektroair.widths.condensed]
shape = 416
menu = 3
css = "condensed"

[buildPlans.iosevka-elektroair.widths.ultraextended]
shape = 720
menu = 9
css = "ultra-expanded"

[buildPlans.iosevka-elektroair.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.iosevka-elektroair.slopes.oblique]
angle = 9.4
shape = "oblique".
menu = "oblique"
css = "oblique"
```

**Comment by be5invis** [comment]
> where I should enter this command. I saw video with entering of this command to some program, but what is it?

Well in a [command-line interface](https://en.wikipedia.org/wiki/Command-line_interface) terminal. Depends on your [operating system](https://en.wikipedia.org/wiki/Operating_system) you are using, it could be:
  * [Command Prompt](https://en.wikipedia.org/wiki/Cmd.exe) on Windows.
  * [Terminal.app](https://en.wikipedia.org/wiki/Terminal_(macOS)) on MacOS.
  * Any terminal application (usually just called "Terminal"), like [GNOME Terminal](https://en.wikipedia.org/wiki/GNOME_Terminal) on Linux.

For the first step you can use ZIP extraction instead of Git cloning. Download [the archive of Iosevka’s source code](https://github.com/be5invis/Iosevka/archive/refs/heads/main.zip) and unzip somewhere on your computer.

> what is `nodejs`, `ttfautohint`

 * Wikipedia page about Node.JS: https://en.wikipedia.org/wiki/Node.js
 * Website of `ttfautohint`: https://freetype.org/ttfautohint/

These are necessary tools to build Iosevka. You need to install them. For Node.JS its installer automatically sets up the [`PATH` environment variable](https://en.wikipedia.org/wiki/PATH_(variable)) so you do not need to configure. `ttfautohint`’s download contain the programs executables directly, so you need to configure the PATH following [this instruction](https://gist.github.com/nex3/c395b2f8fd4b02068be37c961301caa7): you need to add the [directory](https://en.wikipedia.org/wiki/Directory_(computing)) containing the ttfautohint executables (usually named `ttfautohint.exe` or just `ttfautohint`) into your PATH.

You can validate whether Node.JS and `ttfautohint` have installed and successfully configured by running these commands in the terminal:

```bash
node --version
npm --version
ttfautohint --version
```

They should print out the version number of the corresponded tools.

> where I should to enter command npm run build -- contents::iosevka

In the terminal.

Here are the (more detailed?) steps of building the default configuration:

1. Open the terminal.
2. [`cd`](https://en.wikipedia.org/wiki/Cd_(command)) into your directory containing Iosevka source code by running this command:
   ```bash
   cd "<the directlory containing Iosevka source code directly>"
   ```
3. Run this command: `npm install`, this will install more necessary dependencies.
4. Run this command: `npm run build -- contents::iosevka`, this will build the fonts.

For custom build, you need to prepare your `private-build-plans.toml`, and change the command used in step 4 into:

```bash
npm run build -- ttf::iosevka-elektroair
```

The results then could be found in the `dist` subdirectory.

**Comment by Elektroair** [comment]
I have the problem:

```
Microsoft Windows [Version 10.0.19044.1889]
(c) Microsoft Corporation. All rights reserved.

C:\Users\Elektro>cd D:\Elektroair\Iosevka-main

C:\Users\Elektro>npm install

up to date, audited 2 packages in 2s

found 0 vulnerabilities

C:\Users\Elektro>npm run build -- ttf::iosevka-elektroair
npm ERR! Missing script: "build"
npm ERR!
npm ERR! To see a list of scripts, run:
npm ERR!   npm run

npm ERR! A complete log of this run can be found in: C:\Users\Elektro\AppData\Local\npm-cache\_logs\2023-10-12T12_08_26_118Z-debug-0.log
```

This list is from CP of Windows. I installed `Node.JS`, `NPM` and `ttfautohint`:

```
C:\Users\Elektro>node --version
v18.18.1

C:\Users\Elektro>npm --version
9.8.1

C:\Users\Elektro>ttfautohint --version
ttfautohint 1.8.4
```

LOG file of building is in this message.

[2023-10-12T12_08_26_118Z-debug-0.log](https://github.com/be5invis/Iosevka/files/12882233/2023-10-12T12_08_26_118Z-debug-0.log)

Thank you so mach for question! I want to reassure you, I am a confident computer user, and even understand in programming, I am writing a simplified text editor in C#. But unfortunately, I still did not know that there are variables, such as PATH, that add capabilities for the command prompt

**Comment by be5invis** [comment]
> ```
> cd D:\Elektroair\Iosevka-main
> ```

Use `cd /d` instead of just `cd` since you are changing the **drive** too:

> ```
> cd /d D:\Elektroair\Iosevka-main
> ```

(history about why do you need `/d`: https://devblogs.microsoft.com/oldnewthing/20101011-00/?p=12563)

**Comment by Elektroair** [comment]
Thank you! I started to create fonts and I saw ttf files, but for some reason the process always stops at 65-67%, will continue to work very slowly, while the RAM starts to fill up very quickly...

**Comment by be5invis** [comment]
Yes its first run is very slow and uses a lot of memory and CPU time.

**Comment by Elektroair** [comment]
> Yes its first run is very slow and uses a lot of memory and CPU time.

Roger, thanks you!! I will create new builds of Iosevka with enjoy! )

**Comment by alexeyten** [comment]
To speed up the building process you could remove unnecessary weights and widths. E.g. Extra Light or Heavy are not what one would use everyday. But, of course, it's up to you.

<details><summary>E.g.</summary>

```
[buildPlans.iosevka-elektroair.weights.light]
shape = 300
menu = 300
css = 300

[buildPlans.iosevka-elektroair.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.iosevka-elektroair.weights.medium]
shape = 500
menu = 500
css = 500

[buildPlans.iosevka-elektroair.weights.bold]
shape = 700
menu = 700
css = 700

[buildPlans.iosevka-elektroair.widths.normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.iosevka-elektroair.widths.extended]
shape = 600
menu = 7
css = "expanded"

[buildPlans.iosevka-elektroair.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.iosevka-elektroair.slopes.oblique]
angle = 9.4
shape = "oblique".
menu = "oblique"
css = "oblique"

```
</details> 

Also you might want to limit number of parallel tasks with `--jCmd` flag, so that they won't consume all CPU and memory.
```
npm run build -- --jCmd=8 ttf::iosevka-elektroair
```
You could try different numbers instead of `8`.

**Comment by Elektroair** [comment]
Thanks!!
