### ISSUE TITLE
Iosevka doesn't show up in KDE font dialog unless you disable "show only monospace fonts" checkbox

### ISSUE THREAD

**Issue by equeim** [be5invis/Iosevka#2101]
In KDE's font dialog, e.g. in Konsole, Iosevka fonts don't show up unless "show only monospace fonts" is unchecked. So for some reason it's not recognized as monospace?

If I perform `fc-match -a monospace` command in the terminal, then Iosevka does show up though. So maybe it's an issue with KDE, but I don't experience it with other fonts.

I installed it on Fedora through Copr repository, installed packages are `iosevka-term-fonts-27.3.5-1.fc39.noarch` and `iosevka-fonts-27.3.5-1.fc39.noarch`.

**Comment by nsemrau** [comment]
I noticed that `Fixed` versions of the fonts do show up in the KDE font selector dialog by default. Normal and `Term` versions are only selectable after checkmarking the `Shoe all fonts` box. I tested this on the hinted TTF versions.

**Comment by be5invis** [comment]
In the prebuilt packages only Fixed will be compatible with Fontconfig's monospace-ness. Normal and Term variants do contain wider glyphs (for U+27F5, etc.) so that fontconfig will NOT think they are monospace.

This is a by-design behavior as Fontconfig's monospace is considered too strict (they require all encoded characters share same width, which is not feasible for a lot of Unicode characters).

Resolve as by design.
