### ISSUE TITLE
Box Drawing Characters are not monospaced

### ISSUE THREAD

**Issue by myrrlyn** [be5invis/Iosevka#227]
* Your font version: commit 8ba14be
* Your font variant: "sans type ss03 cv01 cv03 cv07 cv13 cv17 cv19 cv21 cv23 cv24 cv30 cv31 cv34 cv37 cv38 cv40 cv42 cv44 cv46"
* Your operating system (name and version): Arch Linux
* Your application using Iosevka: (some Java applications may have problem in showing Iosevka properly. It is a bug in Java's GUI components.) Firefox

Describe your problem here. Provide pictures and files if necessary.

I successfully configured and compiled Iosevka into Woff and Woff2 formats and brought them into my website's stylesheets. When I did so, the box-drawing-character diagrams promptly broke.

Iosevka:
![screen shot 2017-09-22 at 00 25 28](https://user-images.githubusercontent.com/5921109/30731856-10ecd54a-9f2d-11e7-904b-fad8e9899348.png)

Fantasque Sans Mono: 
![screen shot 2017-09-22 at 00 29 45](https://user-images.githubusercontent.com/5921109/30731879-2b3d8bc4-9f2d-11e7-9531-6b832af341e3.png)

Raw text:

```text
A B                                        Cin
║ ║                                         │
║ ╚═══╤════╤════╤════╤════╤════╤════╤════╕  │
╚════╤╪═══╤╪═══╤╪═══╤╪═══╤╪═══╤╪═══╤╪═══╕│  │
    ┌┴┴─┐┌┴┴─┐┌┴┴─┐┌┴┴─┐┌┴┴─┐┌┴┴─┐┌┴┴─┐┌┴┴─┐│
┌───┤ 7 ├┤ 6 ├┤ 5 ├┤ 4 ├┤ 3 ├┤ 2 ├┤ 1 ├┤ 0 ├┘
│   └──┬┘└──┬┘└──┬┘└──┬┘└──┬┘└──┬┘└──┬┘└──┬┘
│ ╔════╧════╧════╧════╧════╧════╧════╧════╛
│ ║
│ Y
│
Cout
```
If you want me to provide a minified compilation script + HTML gist that will demonstrate this behavior, I can do so.

Thanks for your work on this font; other than this issue with the box drawing characters I'm beyond happy with it!

**Comment by be5invis** [comment]
You have “type” in your variation, means that box-drawing glyphs would become full-width (1em wide).

发件人: Alexander Payne<mailto:notifications@github.com>
发送时间: 2017年9月22日 14:33
收件人: be5invis/Iosevka<mailto:Iosevka@noreply.github.com>
抄送: Subscribed<mailto:subscribed@noreply.github.com>
主题: [be5invis/Iosevka] Box Drawing Characters are not monospaced (#227)


  *   Your font version: commit 8ba14be<https://github.com/be5invis/Iosevka/commit/8ba14bef051ccc93f1b063953fe2a3eda747d87b>
  *   Your font variant: "sans type ss03 cv01 cv03 cv07 cv13 cv17 cv19 cv21 cv23 cv24 cv30 cv31 cv34 cv37 cv38 cv40 cv42 cv44 cv46"
  *   Your operating system (name and version): Arch Linux
  *   Your application using Iosevka: (some Java applications may have problem in showing Iosevka properly. It is a bug in Java's GUI components.) Firefox

Describe your problem here. Provide pictures and files if necessary.

I successfully configured and compiled Iosevka into Woff and Woff2 formats and brought them into my website's stylesheets. When I did so, the box-drawing-character diagrams promptly broke.

Iosevka:
[screen shot 2017-09-22 at 00 25 28]<https://user-images.githubusercontent.com/5921109/30731856-10ecd54a-9f2d-11e7-904b-fad8e9899348.png>

Fantasque Sans Mono:
[screen shot 2017-09-22 at 00 29 45]<https://user-images.githubusercontent.com/5921109/30731879-2b3d8bc4-9f2d-11e7-9531-6b832af341e3.png>

Raw text:

A B                                        Cin

U U                                         │

U ^TTThTTTThTTTThTTTThTTTThTTTThTTTThTTTTY  │

^TTTThnTTThnTTThnTTThnTTThnTTThnTTThnTTTY│  │

    ┌┴┴─┐┌┴┴─┐┌┴┴─┐┌┴┴─┐┌┴┴─┐┌┴┴─┐┌┴┴─┐┌┴┴─┐│

┌───┤ 7 ├┤ 6 ├┤ 5 ├┤ 4 ├┤ 3 ├┤ 2 ├┤ 1 ├┤ 0 ├┘

│   └──┬┘└──┬┘└──┬┘└──┬┘└──┬┘└──┬┘└──┬┘└──┬┘

│ XTTTTkTTTTkTTTTkTTTTkTTTTkTTTTkTTTTkTTTT_

│ U

│ Y

│

Cout

If you want me to provide a minified compilation script + HTML gist that will demonstrate this behavior, I can do so.

Thanks for your work on this font; other than this issue with the box drawing characters I'm beyond happy with it!

―

**Comment by myrrlyn** [comment]
s/type/term

![screen shot 2017-09-22 at 00 43 49](https://user-images.githubusercontent.com/5921109/30732314-351d9038-9f2f-11e7-804b-779e3192ce3b.png)

Well that's some egg on my face :/ I somehow did not make the connection between "make some symbols like math operators full-width" in the description on "type" with the box-drawing characters.

Thanks for the quick response.
