### ISSUE TITLE
Possibly reopening several useful issue reports from user @Logo121 whose account has mysteriously vanished from github.

### ISSUE THREAD

**Issue by jmcwilliams403** [be5invis/Iosevka#2361]
Several useful issues raised by @logo121 which were put in the backlog milestone have vanished along with their account. Usually such an incident replaces their issues/PR's/etc. with equivalent posts/logs by a "ghost user" but in this case it left nothing behind.

If possible, does anyone have any past email notifications of their issue reports from having subscribed to this repo which they may copy/paste into new duplicate issues?

**Comment by be5invis** [comment]
I don't have records now 🤷 in either notifications or mail.

**Comment by AndydeCleyre** [comment]
I have mail notifications back to 6/23/23. I exported those messages from gmail to an `.mbox`, then used this command to create the attached `.json` file:

```console
$ <Iosevka-2361.json jq '[.[] | {Date, From, "Message-ID", Subject, "X-GitHub-Sender", Body}]' >upload.json
```

Hopefully it's useful.

[upload.json](https://github.com/user-attachments/files/15538458/upload.json)

**Comment by Logo121** [comment]
My account has been reinstated.

Apparently, my account was flagged because of a large-volume repository that I have pushed to, namely my fork of this repo [Logo121/Iosevka](https://github.com/Logo121/Iosevka).  
I was hence accused of using GitHub as CDN, and was asked to delete that as a requirement for restoring my account.  
I explained that the repo in question was a fork and not something I uploaded, and I was released afterwards, but the ticket was closed without a clear note on whether I will get flagged again if I try to ever make PRs here again.

So... I'm not sure what we can take out of this; I'm not sure if I can even contribute anymore. This issue can be closed now, or maybe repurposed as a discussion on how we can even safely make contributions here without the risk of flagging. Idk.

**Comment by jmcwilliams403** [comment]
> The ticket was closed without a clear note on whether I will get flagged again if I try to ever make PRs here again.
> So... I'm not sure what we can take out of this; I'm not sure if I can even contribute anymore. This issue can be closed now, or maybe repurposed as a discussion on how we can even safely make contributions here without the risk of flagging. Idk.

I'm really disappointed to hear this. You've contributed so many great things to this font project. My own contributions were in part inspired by yours at times. It's so unfortunate that Github is giving you all this trouble over a false positive. I really hope maybe you can still participate in some capacity, but only if you want.
