### ISSUE TITLE
Sorry, I'm really dumb.

### ISSUE THREAD

**Issue by nieqqo** [be5invis/Iosevka#2543]
I really like Iosevka and use it all the time. I recently found out that there is an option to enable Bulgarian Cyrillic. I've dug through everything, but I still haven't figured out how to do it. Can someone give me apps where I can take advantage of this "language localization" and enable Bulgarian Cyrillic?🆘🆘

**Comment by be5invis** [comment]
If you are using Iosevka in webpages, just mark the text's language to Bulgarian.
We do not have features to "bake" localized forms yet.

**Comment by nieqqo** [comment]
so there is absolutely no way to try Bulgarian Cyrillic anymore? it's a shame :(

**Comment by be5invis** [comment]
You can enable Bulgarian localized forms in any text editor that support OpenType and language tagging, i.e., telling it this segment of text is Bulgarian. You can do this in Word too (select the text, then change its language to Bulgarian, and see the text changed to Bulgarian form).

However our current building system does not provide functionality to **bake** localized forms (so they get enabled no matter in what software), since some of them are very complicated. You can try the following third-paty tools, but I do not guarantee that they won't break other font features:

 * https://mutsuntsai.github.io/fontfreeze/
 * https://github.com/twardoch/fonttools-opentype-feature-freezer

**Comment by nieqqo** [comment]
![Picsart_24-10-12_17-20-51-558](https://github.com/user-attachments/assets/f85b46d8-f83c-4b00-94a5-d713f4b3ada0)
which one should I freeze??

**Comment by Logo121** [comment]
Doesn't look like fontfreeze has language freezing. Use the second tool (with the `-l` flag).

**Comment by nieqqo** [comment]
> Doesn't look like fontfreeze has language freezing. Use the second tool (with the `-l 'BGR '` argument).

```
usage: OTFeatureFreezer.exe [-h] [-o [OUTPATH]] [-f FEATURES] [-s SCRIPT]
                            [-l LANG] [-z] [-S] [-U USESUFFIX]
                            [-R REPLACENAMES] [-i] [-r] [-n] [-v]
                            inpath
OTFeatureFreezer.exe: error: argument -l/--lang: expected one argument
```

what does it mean
