### ISSUE TITLE
U+276F Extended version looks too big

### ISSUE THREAD

**Issue by atauzki** [be5invis/Iosevka#2603]
![image](https://github.com/user-attachments/assets/25954c8f-416b-4c75-8d84-7a06c09b697f)

---

* Your font version: 32.2.1
* Your font variant: Fixed
* Your operating system (name and version): Windows 11 26100
* Your application using Iosevka: Windows Terminal

**Comment by be5invis** [comment]
About height or width?

**Comment by atauzki** [comment]
mainly height

**Comment by atauzki** [comment]
the height

**Comment by jmcwilliams403** [comment]
FWIW one of the pairs of dingbat ornamental angle "brackets" (`❮`/`❯`) is actually supposed to be based on guillemets (`‹`/`›`) not angle brackets (`⟨`/`⟩`) hence its different name in Unicode than the other two pairs (`❬`/`❭`/`❰`/`❱`).

**Comment by be5invis** [comment]
Resolved in #2623. This symbol now follows Guillmets' dimension.

**Comment by real-or-random** [comment]
> FWIW one of the pairs of dingbat ornamental angle "brackets" (`❮`/`❯`) is actually supposed to be based on guillemets (`‹`/`›`) not angle brackets (`⟨`/`⟩`) hence its different name in Unicode than the other two pairs (`❬`/`❭`/`❰`/`❱`).

That's certainly true, but given that these are dingbats and in particular ornaments, that doesn't mean that the dimensions need to be the same. And most fonts seem to make them tall. See for example page 4, top left corner, of the [Unicode spec PDF](https://www.unicode.org/charts/PDF/U2700.pdf) for a direct comparison with the normal quotation marks. (I'm aware that the shapes are not normative) 

These ornaments are often used as a terminal prompt (as in the screenshot in the opening comment) because they are tall in most fonts, e.g., the tide prompt for the fish shell uses these.

So this fix broke/changed my prompt, and I assume this will affect many many users.

Sure, I can change my prompt to use a different character (and I will), but since there is no clear right or wrong here, I believe reverting this change will be a good thing for most users.

**Comment by Ved-un** [comment]
Don't do that, fix it back to the way it was, please.

This has disfigured the prompt in the terminal for many people.

**Comment by Logo121** [comment]
It's probably not my call to make on how the glyph should be rescaled, but meanwhile, if you want the original shape back (and have been building your own configurations anyway), you can change these 2 lines in the source code
https://github.com/be5invis/Iosevka/blob/5a346deb0f8185b4ce55f36a0c4a925831b4b4fc/packages/font-glyphs/src/symbol/pictograph/checking-marks.ptl#L80-L81

to use the same left/top bound (last 2 `[mix ...]` terms) as the other dingbat bracket pairs:
https://github.com/be5invis/Iosevka/blob/5a346deb0f8185b4ce55f36a0c4a925831b4b4fc/packages/font-glyphs/src/symbol/pictograph/checking-marks.ptl#L78-L79

**Comment by be5invis** [comment]
#2648 should solve this. Height is now selectable.

**Comment by ryankask** [comment]
Is there a character variant for this or does using the older version require a custom build? I suspect this will impact [Starship](https://github.com/starship/starship) + Iosevka users.
