### ISSUE TITLE
Do not round components' coordinates in the unhinted variant

### ISSUE THREAD

**Issue by rmtracey** [be5invis/Iosevka#273]
* Your font version: (Release or git, version) Release, 1.14.2
* Your font variant: Default and Terminal, with default styles, hinted and unhinted
* Your operating system (name and version): Windows 10 and Windows 7
* Your application using Iosevka: (some Java applications may have problem in showing Iosevka properly. It is a bug in Java's GUI components.) Visual Studio Code, Hyper, Google Chrome, Cmder

---

Describe your problem here. Provide pictures and files if necessary.

The bars in the "triple bar" character in Iosevka are misaligned at many font sizes in various applications. This is quite jarring visually for anyone who uses posh-git on Windows, where this character is prominently used.

There doesn't seem to be a size threshold where the bars start to align properly, either - they only seem to be evenly spaced at a handful of seemingly unrelated sizes. For example, it looks fine at sizes 18-19 and 25-26 in VSCode and Hyper, but it looks wrong at just about every size in-between. Start increasing the font size again, and it will start looking wrong again up until size 31-32. Cmder shows the same behavior, but the sizes where it looks "right" are slightly different.

Some examples:
Size 14:
![hyper_2018-05-16_18-39-26](https://user-images.githubusercontent.com/3460875/40147739-e1a32624-5938-11e8-8752-96169e074a9f.png)

Size 18:
![hyper_2018-05-16_18-39-54](https://user-images.githubusercontent.com/3460875/40147757-fd21dd32-5938-11e8-9b27-a498a01ebb64.png)

Size 22:
![hyper_2018-05-16_18-40-14](https://user-images.githubusercontent.com/3460875/40147766-06afeefc-5939-11e8-88da-6d8cc4289859.png)

Size 26:
![hyper_2018-05-16_18-40-26](https://user-images.githubusercontent.com/3460875/40147793-14ae7c08-5939-11e8-80c2-0ae33a5a8cce.png)

Size 30:
![hyper_2018-05-16_18-40-41](https://user-images.githubusercontent.com/3460875/40147801-1cba0386-5939-11e8-9711-d28f23a2861c.png)

Size 32:
![hyper_2018-05-16_18-40-52](https://user-images.githubusercontent.com/3460875/40147811-22c780aa-5939-11e8-80d5-50b669935c9d.png)

**Comment by be5invis** [comment]
You can try the unhinted version.

发自我的 iPhone

在 2018年5月17日，06:50，rmtracey <notifications@github.com<mailto:notifications@github.com>> 写道：


  *   Your font version: (Release or git, version) Release, 1.14.2
  *   Your font variant: Default and Terminal, with default styles, hinted and unhinted
  *   Your operating system (name and version): Windows 10 and Windows 7
  *   Your application using Iosevka: (some Java applications may have problem in showing Iosevka properly. It is a bug in Java's GUI components.) Visual Studio Code, Hyper, Google Chrome, Cmder

________________________________

Describe your problem here. Provide pictures and files if necessary.

The bars in the "triple bar" character in Iosevka are misaligned at many font sizes in various applications. This is quite jarring visually for anyone who uses posh-git on Windows, where this character is prominently used.

There doesn't seem to be a size threshold where the bars start to align properly, either - they only seem to be evenly spaced at a handful of seemingly unrelated sizes. For example, it looks fine at sizes 18-19 and 25-26 in VSCode and Hyper, but it looks wrong at just about every size in-between. Start increasing the font size again, and it will start looking wrong again up until size 31-32. Cmder shows the same behavior, but the sizes where it looks "right" are slightly different.

Some examples:
Size 14:
[hyper_2018-05-16_18-39-26]<https://nam03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F3460875%2F40147739-e1a32624-5938-11e8-8752-96169e074a9f.png&data=02%7C01%7C%7C990e889e72da4d1143d608d5bb7f7603%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636621078476990968&sdata=46sRIz7pHodlIRGZ2ZUozyi53p%2Fcuy%2BreTphcVe26ls%3D&reserved=0>

Size 18:
[hyper_2018-05-16_18-39-54]<https://nam03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F3460875%2F40147757-fd21dd32-5938-11e8-9b27-a498a01ebb64.png&data=02%7C01%7C%7C990e889e72da4d1143d608d5bb7f7603%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636621078476990968&sdata=CzUCW5UK4gUCIUszzkltfLiWdHSxxqoOwccM0mzgRHI%3D&reserved=0>

Size 22:
[hyper_2018-05-16_18-40-14]<https://nam03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F3460875%2F40147766-06afeefc-5939-11e8-88da-6d8cc4289859.png&data=02%7C01%7C%7C990e889e72da4d1143d608d5bb7f7603%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636621078476990968&sdata=6ANc%2BZxG9d%2FESFTe79sxN62sVssnRV%2BihibLkCKqxwU%3D&reserved=0>

Size 26:
[hyper_2018-05-16_18-40-26]<https://nam03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F3460875%2F40147793-14ae7c08-5939-11e8-80c2-0ae33a5a8cce.png&data=02%7C01%7C%7C990e889e72da4d1143d608d5bb7f7603%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636621078476990968&sdata=OVNs6bBs%2FeD%2BaP25imuxuqwCUXALfIpSriQLAzlxCzI%3D&reserved=0>

Size 30:
[hyper_2018-05-16_18-40-41]<https://nam03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F3460875%2F40147801-1cba0386-5939-11e8-9711-d28f23a2861c.png&data=02%7C01%7C%7C990e889e72da4d1143d608d5bb7f7603%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636621078476990968&sdata=yk0dG7zgtQ%2FPnmm3Gxsyzfe6edny0IM8ECadoKKaXBE%3D&reserved=0>

Size 32:
[hyper_2018-05-16_18-40-52]<https://nam03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F3460875%2F40147811-22c780aa-5939-11e8-80d5-50b669935c9d.png&data=02%7C01%7C%7C990e889e72da4d1143d608d5bb7f7603%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636621078476990968&sdata=GvOinGW%2BleZjCrBIAIRtI10L%2B44afhkbNELWEae9bVM%3D&reserved=0>

**Comment by rmtracey** [comment]
My screen is about 141 PPI - not sure how high density I would have to have to "justify" using the unhinted version. Regardless, I use the unhinted version anyway, because the hinted version has issues with the vertical alignment of the equals sign for me. Regardless, this happens with the hinted and unhinted versions - I've tried both.

**Comment by rmtracey** [comment]
Sorry, image of what? The hinted version? The triple bar looks the same for me on the hinted and unhinted versions.

**Comment by be5invis** [comment]
Image of Unhinted.

发自我的 iPhone

在 2018年5月17日，20:54，rmtracey <notifications@github.com<mailto:notifications@github.com>> 写道：


Sorry, image of what? The hinted version? The triple bar looks the same for me on the hinted and unhinted versions.

**Comment by rmtracey** [comment]
The images that I initially posted are of the unhinted version. I can take some screenshots of the hinted version later today if needed (I'm at work), but the appearance of the triple bar is the same for me on both.
