### ISSUE TITLE
iosevka for web

### ISSUE THREAD

**Issue by pvinis** [be5invis/Iosevka#337]
* Your font version: 2.2.1
* Your font variant: -
* Your operating system (name and version): macos
* Your application using Iosevka: (some Java applications may have problem in showing Iosevka properly. It is a bug in Java's GUI components.)

---

I want to add iosevka on my website. I added everything, included etc. My question is, should I use it as `'Iosevka'` or `'Iosevka Web'`? Because on the `webfont.css` file, the name there is with `Web`.

**Comment by be5invis** [comment]
Follow the CSS files generated in dist/ after building.

________________________________
发件人: Pavlos Vinieratos <notifications@github.com>
发送时间: Wednesday, June 12, 2019 7:04:14 AM
收件人: be5invis/Iosevka
抄送: Subscribed
主题: [be5invis/Iosevka] iosevka for web (#337)


  *   Your font version: 2.2.1
  *   Your font variant: -
  *   Your operating system (name and version): macos
  *   Your application using Iosevka: (some Java applications may have problem in showing Iosevka properly. It is a bug in Java's GUI components.)

________________________________

I want to add iosevka on my website. I added everything, included etc. My question is, should I use it as 'Iosevka' or 'Iosevka Web'? Because on the webfont.css file, the name there is with Web.

―

**Comment by pvinis** [comment]
So `Iosevka Web` then?

**Comment by be5invis** [comment]
Yes.

________________________________
发件人: Pavlos Vinieratos <notifications@github.com>
发送时间: Wednesday, June 12, 2019 8:28:50 AM
收件人: be5invis/Iosevka
抄送: Belleve Invis; Comment
主题: Re: [be5invis/Iosevka] iosevka for web (#337)


So Iosevka Web then?

―

**Comment by pvinis** [comment]
Hm, ok. Thanks :D
