### ISSUE TITLE
Rethink the % operator

### ISSUE THREAD

**Issue by cata0309** [be5invis/Iosevka#344]
* Your font version: (Release or git, version) 2.2.1
* Your font variant: Iosevka Default
* Your operating system (name and version):  Solus Linux Fortitude
* Your application using Iosevka: (some Java applications may have problem in showing Iosevka properly. It is a bug in Java's GUI components.) doesn't matter as it is not a bug

Describe your problem here. Provide pictures and files if necessary.
Iosevka default and Iosevka Term default:
![image](https://user-images.githubusercontent.com/35623921/62032267-ef356780-b1f1-11e9-9624-49d117f61e1c.png)
![image](https://user-images.githubusercontent.com/35623921/62032282-f78da280-b1f1-11e9-93fe-e0cd74156a81.png)

Iosevka SS05,SS11,Term SS05,Term SS07(and I think other variants too)
![image](https://user-images.githubusercontent.com/35623921/62032354-1b50e880-b1f2-11e9-8aa2-07441f393084.png)

The default one looks to tiny and I think it can be improved.

**Comment by be5invis** [comment]
Currently Iosevka's `%` should default to the circled one.

**Comment by cata0309** [comment]
I will look at the fonts. I think I did choose the wrong one

**Comment by be5invis** [comment]
The variants are used to mimick other fonts, following their design (dots vs circles).

**Comment by cata0309** [comment]
Nop, it is the default one, not a mimick

**Comment by be5invis** [comment]
@cata0309 
Here is the `iosevka-regular.ttf` directly shown in OTM (a very famous tool to inspect a font's internals)

![image](https://user-images.githubusercontent.com/240091/62032952-bf5d7400-b19f-11e9-8226-f670cd796465.png)

Percent symbol (U+0025) is mapped to the circled variant.

I do not know what happened to your application but it seems that an OpenType feature (like `cv62`) is enabled so it changed the shape of `%`. Or your system cannot properly handle Iosevka's OT stuff —— since I am almost "abusing" OpenType lyaout.

**Comment by cata0309** [comment]
You are right ! How is it that this issue happens on TTF versions if you used OpenType feature?

**Comment by be5invis** [comment]
@cata0309 
Well, currently you can think `TrueType` is identical to `OpenType`.
OS/software may unintentionally enable some OT features that distort your output.

**Comment by cata0309** [comment]
I understand, I had some issues in the past with some missing glyphs and I am sure it is the same cause. I see you are using Windows 10.
