### ISSUE TITLE
Issue with alignment of left-pointing powerline arrows in vim-airline

### ISSUE THREAD

**Issue by Hazza4569** [be5invis/Iosevka#353]
* Your font version: 2.3.0
* Your font variant: Iosevka
* Your operating system: Fedora 30
* Your application using Iosevka: rxvt-unicode

Describe your problem here. Provide pictures and files if necessary.

Using Iosevka as my terinal font, the powerline on the right hand side doesn't display correctly. The powerline arrow is not flush with the rest of the bar. The left hand side is fine under the default settings. I have tried to adjust the shift and scale of the powerline symbols, but I can't find a solution which renders both sides correctly.

![2019-09-05-131512_932x34_scrot](https://user-images.githubusercontent.com/16745769/64341052-7939d280-cfdf-11e9-97f5-fd54f143ad40.png)

**Comment by Hazza4569** [comment]
Actually, a bit more experimentation and I have managed to fix it...
Here's my build parameters if anybody else has the same issue:
```
[buildPlans.iosevka-pl]
family = "IosevkaPL"
design = ["powerline-shift-x-n50","powerline-scale-y-1125"]
```

I had to move both arrows inwards with the x-shift, and then use the y scale to fix the overcompensation of the shift.

**Comment by OJFord** [comment]
Note that in the current version (at time of writing) the configuration above is:
```toml
[buildPlans.iosevka-pl]
family = "IosevkaPL"

[buildPlans.iosevka-pl.metric-override]
powerlineShiftX = -50
powerlineScaleY = 1.125
```

However, I had the same problem, but found `-25` and `1.06125` respectively to be better values (and to behave better, not perfectly, but better, at different font sizes - i.e. when changing them by 'zooming' in/out in the terminal).

The `metric-override` section comes with a warning discouraging using it, and indeed I'd rather not have to make such low-level customisation, but can you give any clue as to what the issue is that requires this workaround @be5invis?
