### ISSUE TITLE
Iosevka Aile suggestion

### ISSUE THREAD

**Issue by InBetweenNames** [be5invis/Iosevka#357]
Absolutely love Iosevka Aile -- I just wanted to draw your attention to the fact that a lowercase `l` and a capital `I` look identical in the font.  I've tried toying with a few settings to differentiate them but I haven't found anything I'm satisfied with.  Is this something that might be fixable?

It also seems to work great with ligatures enabled.

**Comment by be5invis** [comment]
Iosevka Aile is **not** a programming font, it is more like Helvetica so this is a by-design.

**Comment by InBetweenNames** [comment]
With a little work, it could make for an amazing proportional programming font.  Just look at this screenshot -- it's quite nice!

![image](https://user-images.githubusercontent.com/7820684/66270455-eaa8b300-e821-11e9-804f-679d5f94da89.png)

**Comment by polarathene** [comment]
> Iosevka Aile is **not** a programming font

@be5invis I'm a little confused what Aile and Etoile have to do with Iosevka then?

> Iosevka is a slender monospace sans-serif and slab-serif typeface inspired by Pragmata Pro, M+ and PF DIN Mono, designed to be the ideal font for programming. - [Source](https://typeof.net/Iosevka/)

> Slender typeface for code, from code. - [Source](https://github.com/be5invis/Iosevka)

Is that definition changing in future?

While discussing such, those links point out stylistic sets with preview of various other known font names. It's not entirely clear what is meant here. Are the highlighted glyphs/characters all being replaced with equivalents to what those fonts provide? But only the highlighted(which all fonts seem to highlight the same characters), meaning that it's not completely mimicking another font, just a portion of it's style?

**Comment by InBetweenNames** [comment]
I'm strongly considering taking the time to make my own variant based off Aile which is more suitable for programming.  It really is nice when it works.

**Comment by mikehamer** [comment]
Adding my enthusiasm for this suggestion!

**Comment by jkyeung** [comment]
@polarathene - I agree completely: if it's a variant of Iosevka, then by its nature it is well-suited to programming. The only things to add are the programming-specific touches that Iosevka already had.

And fortunately, it seems like Aile and Etoile now **do** have them! This makes the full Iosevka family a strong alternative to Input and Recursive, in the "mildly proportional coding font" space. I had kind of given up on this font due to [this comment](https://github.com/be5invis/Iosevka/issues/357#issuecomment-537309635) and quick closure of the issue. But now we can say its status is "closed - implemented" rather than "closed - won't fix"! Wonderful!
