### ISSUE TITLE
[Glyph Request] curly variants for k, x and z

### ISSUE THREAD

**Issue by wimstefan** [be5invis/Iosevka#362]
* Your font version: git latest master - currently b92ca29a
* Your font variant: Iosevka Term customized
* Your operating system (name and version): Linux Gentoo
* Your application using Iosevka: terminals

I *love* the tailed 'f' you created some time ago and I also use the curly version of 'y'.
Would it be possible to create curly versions of the letters 'k' and 'z' as used in IBM Plex Mono Italic and 'x' as used in Overlock? Please see the pictures below for illustration ...

![IBM-Plex-Mono-Italic-k](https://user-images.githubusercontent.com/4605934/66205707-5bc75980-e6ae-11e9-927d-590faf91cbfe.png)
![IBM-Plex-Mono-Italic-z](https://user-images.githubusercontent.com/4605934/66205717-62ee6780-e6ae-11e9-8012-1f5fc4754962.png)
![Overlock-Regular-x](https://user-images.githubusercontent.com/4605934/66205724-671a8500-e6ae-11e9-89a8-4f0c4d69affb.png)

**Comment by tomByrer** [comment]
Would be a nice addition to the ittalics.  Though I would prefer a slightly more arched diangular bar on teh Z, similar to the X perhaps?

**Comment by AndydeCleyre** [comment]
Here's another comparison shot of the fonts mentioned, along with Baumans (which does a nice job with `z` and `Z`) and Ruluko (which is close to Overlock with `k` and `x`):

![image](https://user-images.githubusercontent.com/1787385/71120613-c6b30780-21aa-11ea-9b17-b6977eb8858b.png)

I have no complaints about Iosevka's existing `kKxX` set, but wouldn't mind a more curvaceous `zZ` set as long as it doesn't look too similar to `2`.

**Comment by wimstefan** [comment]
I saw that you integrated `v-k-cursive` ... many thanks for that!
Unfortunately the loop looks a bit squashed when using `condensed` in `private-build-plans.toml` so I went back to `v-k-curly`.

**Comment by akarzim** [comment]
@be5invis `K` and `X` have their curly variant. What about `Z`?  
Maybe something like this:

<img width="215" alt="image" src="https://user-images.githubusercontent.com/130560/92004940-23f3e680-ed43-11ea-86cf-458fbbe583f5.png">

**Comment by akarzim** [comment]
@be5invis what about this curly `z` variant for the final 4.0.0 ? It would be great :)

**Comment by kauesena** [comment]
@be5invis I've seen this issue was closed, but I would like to suggest an even curlier version of the current alternatives. 
I assume that, in the images below, the curly z that was added is the fourth and the curly x that was added is the second.  
![image](https://user-images.githubusercontent.com/30255100/104791846-e6847880-577a-11eb-829a-8c9f356e4c82.png)
![image](https://user-images.githubusercontent.com/30255100/104791920-3d8a4d80-577b-11eb-9dcf-8ea01980aaf4.png)
It would be great to have an even curlier alternatives such as the IBM Plex one:
![image](https://user-images.githubusercontent.com/30255100/104791970-76c2bd80-577b-11eb-83af-dc7368f377a3.png)

**Comment by kauesena** [comment]
At first, when I saw such characters in IBM Plex Mono Italic, I thought they were too much. Nowadays, I love them. Specially the z.

**Comment by wimstefan** [comment]
That was my initial request ... ;)

**Comment by NoxUltima** [comment]
How about those from Recursive Mono as well? #852
