### ISSUE TITLE
Add support for stylistic set based on Fira Code

### ISSUE THREAD

**Issue by baco** [be5invis/Iosevka#430]
* Your font version: 3.0.0b3
* Your font variant: Default
* Your operating system (name and version): Debian (sid/unstable)
* Your application using Iosevka: Neovim-GTK

Add support for stylistic set based on Fira Code in addition to the support of Fira Mono.  FiraCode has many characters that differ from Fira Mono.

**Comment by be5invis** [comment]
I think I already have a lot?
![](https://raw.githubusercontent.com/be5invis/Iosevka/master/images/stylesets.png)

There are also `cv##` tags:
![](https://raw.githubusercontent.com/be5invis/Iosevka/master/images/charvars.png)

**Comment by paolobolzoni** [comment]
Perhaps what is needed is an easier way to setup and compile variants? Maybe a simple docker setup where one can easily give the ```private-build-plans.toml``` file and get the fonts on output? About this point I can help if you want.

Secondly, it is kinda a pity that in the ```cv##``` table there aren't the easy-to-understand names.

Thirdly, since the compilation is fairly long it is difficult to play around with the language. A way to make only a subsets of the glyphs or a "preview mode" would be very useful.


I am aware I bumping my unsolicited opinion, but am I seeing this pattern of asking for yet another variant often and the combinatorial explosion simply makes impossible to give everyone their own favorite variant. For example, I like the flat-head 3, just for this I am confined to only one of the pre-existing variants.

**Comment by be5invis** [comment]
@paolobolzoni

> Perhaps what is needed is an easier way to setup and compile variants? Maybe a simple docker setup where one can easily give the private-build-plans.toml file and get the fonts on output? About this point I can help if you want.
> 
> Thirdly, since the compilation is fairly long it is difficult to play around with the language. A way to make only a subsets of the glyphs or a "preview mode" would be very useful.

OT features are already included in the prebuilt versions. **You can just enable them in you editor.** They can also be used to create a custom build with the features **enabled by default** to support applications that do not support advanced shaping, like Notepad.

> Secondly, it is kinda a pity that in the `cv##` table there aren't the easy-to-understand names.

OT feature tags only support 4 ASCII characters. So, you have no choice 🤷‍♀.

**Comment by paolobolzoni** [comment]
> OT features are already included in the prebuilt versions. **You can just enable them in you editor.** They can also be used to create a custom build with the features **enabled by default** to support applications that do not support advanced shaping, like Notepad.

That's... interesting. Since I work via ```ssh``` most of the time, my editor is basically limited to what ever Msys2 gives me (I think it is mintty) and I am fairly sure one cannot decide what features are used.
Oh, well.. good to know for the future.

 
> > Secondly, it is kinda a pity that in the `cv##` table there aren't the easy-to-understand names.
> OT feature tags only support 4 ASCII characters. So, you have no choice 🤷‍♀.

I think we are not on the same page, I was just thinking to the preview picture:
https://raw.githubusercontent.com/be5invis/Iosevka/master/images/charvars.png
When I wrote my ```private-build-plans.toml``` I was keeping that picture open, and I so I wrote in the ```buildPlans.design``` array the hard-to-understand names.
Would be difficult to add the easy-to-understand names to the picture? I can see they are longer, so perhaps is really a problem.

**Comment by be5invis** [comment]
@paolobolzoni Easy-to-read style names?
Follow this section: https://github.com/be5invis/Iosevka#build-your-own-style
