### ISSUE TITLE
Support for Hack Zero Style

### ISSUE THREAD

**Issue by cprog** [be5invis/Iosevka#437]
Please add support for Hack style zero glyph 
Look at this picture:

![HackZero](https://user-images.githubusercontent.com/8316463/76209800-6cef3600-620b-11ea-9246-96e21a569f50.png)

**Comment by be5invis** [comment]
IDK whether this is the right interpretation of your desired style, the shape of Iosevka's `0` is very different from Hack, so having a long dot inside may look strange (right is the dotted `0` and slashed `0`).

![image](https://user-images.githubusercontent.com/240091/82741670-83d0ff00-9d09-11ea-91e3-3fc3d42d79ee.png)

![image](https://user-images.githubusercontent.com/240091/82741669-7ae02d80-9d09-11ea-9c45-e9acc625a16c.png)
![image](https://user-images.githubusercontent.com/240091/82741672-8fbcc100-9d09-11ea-9f4b-c4b8576930ba.png)

**Comment by nsemrau** [comment]
> IDK whether this is the right interpretation 

Hmmm ... I think to emulate the style better, the dot should be a vertical ellipse instead of a vertical line with rounded edges. Hack's author once called it "the eye of Sauron". :laughing:

[Hack's homepage](https://sourcefoundry.org/hack/) shows the 0 in a huge size for a detailed look.

But please don't overdo it, if you think this is too much unneccesary work or technically not feasible to implement for such a minor detail.

**Comment by be5invis** [comment]
But don't you think an ellipse in a oval-y-with-straight-sides zero is strange?

**Comment by be5invis** [comment]
Reducing the length seems work better
![image](https://user-images.githubusercontent.com/240091/82742813-57bc7a80-9d17-11ea-8e8d-f5b6b4d156aa.png)

**Comment by nsemrau** [comment]
To be honest, the forced introduction of this dotted zero was one of the reasons I switched to Iosevka, since I like the slashed zero best. Once again, thank you for all your work here. :)

I guess it comes down to how much you want to stay true to the (admittedly slightly weird) original. If you as the decision maker of this font are not fond of the ellipsis, this is a good compromise.

BTW, I remember that the introduction of this glyph in Hack was a bit controversial at the time. So maybe some users of Hack will switch to this Iosevka variant. :laughing:

**Comment by cprog** [comment]
> Reducing the length seems work better
> ![image](https://user-images.githubusercontent.com/240091/82742813-57bc7a80-9d17-11ea-8e8d-f5b6b4d156aa.png)

@be5invis Thank you very much for your hard work.
I really like this variant ! :) 
I even think it is much better than zero in Hack

**Comment by be5invis** [comment]
OK, case closed, it will be added into version 3.1.0 under tag `CVAB`.
