### ISSUE TITLE
Support for square dot option

### ISSUE THREAD

**Issue by k1-k0** [be5invis/Iosevka#512]
Hi Belleve,

What about the square dot variants for `.`, `,`, `:`, `;`, `?`, `!` symbols like as in _Meslo_ font?

**Comment by be5invis** [comment]
Mark as post-3.0 feature request.

**Comment by alexeyten** [comment]
https://github.com/be5invis/Iosevka/issues/140#issuecomment-341637923

**Comment by be5invis** [comment]
I'd like to mark this as Needs Justification. Rounded dots is considered as a design feature rather than a variant shape. Also adding them requires a major rewrite of many parts of the building system.

**Comment by k1-k0** [comment]
Thank you for the answer!

This option is just my personal taste, and I think that the font with square dots may look more strict, so anyway I understand that my flavor is not a reason for big rewrites for you. Although I still think that without this feature, the font looks very attractive and harmonious

**Comment by paolobolzoni** [comment]
I do not know if it counts as justification, but I am interested in trying square dots too because my system display the fonts quite sharp and so since I use iosevka in a small size often the dots look kinda "squarey" anyhow to align to pixel boundaries.
So I wonder if having them as real squares would look nicer.

Still, if a major rewrite is needed, I understand it is not worthwhile.
