### ISSUE TITLE
No variant for l with middle dot

### ISSUE THREAD

**Issue by AlsoScratch** [be5invis/Iosevka#566]
There are no character variants for `l` with a middle dot (U+0140) in 3.1.0.

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/83344239-ccb02700-a2b8-11ea-9fd0-3730fd4646cd.png)

**Comment by throwaway571** [comment]
@be5invis Can we get the dot moved somewhat to the right? In Catalan, it should be exactly centered between two `l`s, which is the only situation when this character occurs.

**Comment by be5invis** [comment]
@throwaway571 A later modification is doing that, ensuring the dot will not collide with the bar.

**Comment by throwaway571** [comment]
@be5invis What about the three-character sequence `l·l`? The precomposed `ŀ` is a deprecated compatibility character in Unicode, and the recommended representation for the Catalan geminated l is `l·l`. Now, Catalan typographers insist that it should take up only two spaces, but I don’t like the disparity, especially because this is a code font.

**Comment by be5invis** [comment]
@throwaway571 Iosevka's ligations will **never** change the space. Therefore `l·l` will be kept having 3 units.
