### ISSUE TITLE
Question: are curves algorithmically generated for Iosevka?

### ISSUE THREAD

**Issue by pagerc** [be5invis/Iosevka#641]
Feature request:
Detailed documentation surrounding how Iosevka generates fonts and variants on the main webpage.

I found Agave font:
https://b.agaric.net/page/agave

And being able to define curves based on a function seems like a neat idea for altering the style of Iosevka.

**Comment by be5invis** [comment]
Well it is a hybrid of clothoids, superellipses, offset curves, and so on. I just pick the one that could create the best shape I need.
Some parameters (like `superness`) could bend the arcs around but changing them is very discouraged: you can easily create broken shapes with that.
Since its internals may refactor more in 4.0, writing docs for current implementation may not be a good idea. Close this for now and I will start a new issue tracking future doc works.
