### ISSUE TITLE
Remove "Oblique" from family name in oblique fonts

### ISSUE THREAD

**Issue by efermi** [be5invis/Iosevka#733]
Oblique fonts have "Oblique" in their family name, unlike italic, and that confuses many applications, for example all(?) Qt applications such as KWrite here. At the screenshot you can see that they are listed as a separate family and that breaks the grouping in the presence of a subfamily such as the Extended variant. In this case if the Extended variant is selected the program would render faux italic (oblique) instead.

![Screenshot_20201115_023544](https://user-images.githubusercontent.com/3966555/99159171-5af35a80-26eb-11eb-89ac-935db7eb8454.png)

**Comment by be5invis** [comment]
Closing as by design. It looks like your software organizes fonts in RBIZ model, which one family cannot contain both Italic and Oblique. As a result, Oblique subfamilies will become a separate family to be compatible with theses software.

See [`name` table in the Spec](https://docs.microsoft.com/en-us/typography/opentype/spec/name) for more information.

**Comment by efermi** [comment]
Understood, thank you for pointing this out.
