### ISSUE TITLE
Base-serifed version of r (Decima Mono)

### ISSUE THREAD

**Issue by NoxUltima** [be5invis/Iosevka#851]
- [x] The requested variant shape does not go too far away from Iosevka's design.
- [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [x] Some other monospace/programming fonts supported the requested variant. Provide images below.

------

Since `r` already has a `serifed` and a `top-serifed` variant, what about a `base-serifed` version too?

![](https://render.myfonts.net/fonts/font_rend.php?id=d96cd353eba10be132fc148ebbbcb006&rbe=gmap&t=s&acs_w=720&acs_glyph_list=41)

![](https://cdn.myfonts.net/s/aw/720x360/446/0/228726.png)

**Comment by be5invis** [comment]
I have a question.
Are you browsing through MyFonts, and hoping Iosevka to implement every letterform you saw?
Repeat my words: I still want some consistency among the letterforms, instead of making Iosevka become a super-font that contains everything.

**Comment by NoxUltima** [comment]
> Are you browsing through MyFonts, and hoping Iosevka to implement every letterform you saw?
No. Not at all.

**Comment by pv4** [comment]
@NoxUltima , just curious, do you personally use a build including all the variants @be5invis implemented for your issues? (I personally use at least `five` suggested by you and it's beautiful).

Excuse me if it's not my business, but do you know Iosevka supports many languages besides English and many letter shapes of those languages depend on shapes of similar (or not even similar) English letters? E.g. greek `mu` shape depends on latin `u` shape. Implementing a new letter shape implies ensuring that depending letters are not damaged by the change, that is much more of work than just draw a new shape.

I'm not sure this font could be done by someone who is not a linguist because I often saw it takes into account very individual characteristics of non-English letters.

@be5invis , Iosevka is a really great font and I know it's a hard work to make and support it. That's true and that's why you often see similar messages in other issues. Thanks for your hard work from yet another happy user!

**Comment by NoxUltima** [comment]
@pv4 Um, yes I do. And tbh I **loved** how he'd done it.

> Iosevka supports many languages besides English and many letter shapes of those languages depend on shapes of similar (or not even similar) English letters

True. For some reason I forgot... my bad. I sincerely apologize, @be5invis, if I sounded like I expected too much from his work. That's why I posted a new issue #854 that's kind of a "tribute/regret" looking back from all the issues I've posted.

> Implementing a new letter shape implies ensuring that depending letters are not damaged by the change, that is much more of work than just draw a new shape.

I knew this was hard for him...

**Comment by be5invis** [comment]
@NoxUltima It's fine to file issues to me — but please double check that the variant you added will not damage dependent letters, and is it **did** harmonize with existing letterforms, especially the _default_ letterform.

**Comment by NoxUltima** [comment]
@be5invis Got you. Thanks for the reply. You really did a good job there. I appreciate it 😁

**Comment by be5invis** [comment]
Also one thing may need notice: requesting one variant usually not meaning adding one variant into the font, but adding a new _dimension_ of variation into it. Just look at `G`, it is a 3 × 3 × 3 cube of variants, to simply allow the user to pick what they want.

**Comment by NoxUltima** [comment]
PS: I once thought of making the bars of `f` and `t` asymmetric but that would double it again. `f` already has 20 after the addition of diagonal tails so adding asymmetric versions would make it 40...
