### ISSUE TITLE
Iosevka Term Slab: PFM Family is "Serif", should be "Monospace"

### ISSUE THREAD

**Issue by nickexton** [be5invis/Iosevka#877]
Iosevka Term Slab is not available for use in some programs that allow only monospace fonts (e.g. terminal emulators). The problem appears to be that it identifies itself as "Serif" instead of "Monospace".

Specifically, it can't be set as a font for the Terminal application in Ubuntu.

Similar to this Inconsolata issue: https://github.com/google/fonts/issues/2686

---

* Your font version: (Release or git, version)
5.0.0-beta.3

* Your font variant:
Iosevka Term Slab

* Your operating system (name and version):
Ubuntu 20.04

* Your application using Iosevka: 
Terminal

**Comment by be5invis** [comment]
PFM Family doesn’t make sense for OpenType as it is only for Type 1 fonts.
Being “not available for use in some programs that allow only monospace fonts” is due to FontConfig’s reorganization algorithm: it **forces** all non-combining characters to have the exact same width, which doesn’t apply to Iosevka since we support certain larger symbols. Iosevka Fixed should work in these applications (and this is why Iosevka Fixed existed).

**Comment by nickexton** [comment]
Thanks for the quick response. 

I've confirmed that Iosevka Fixed works, so I'll close this issue.
