### ISSUE TITLE
cf8c550 and cyrl/be shape change

### ISSUE THREAD

**Issue by pv4** [be5invis/Iosevka#901]
The commit cf8c550 "Shape refinement of grek/delta and cyrl/be" decreased the height of the circle of `cyrl/be`. Before that it was of `x-height` height. Now it's less than that and this's the only cyrillic (russian) letter that doesn't align with x-height, that being looking strange/inconsistent.

It would not be an issue if there were some other letters being "not x-height" (or for fancy fonts among which the most known are `microsoft comic sans` and `samsung choko cooky`) as could be found on some sites with fonts to buy/download. But for Iosevka it doesn't seem to be the case since Iosevka style looks more solid, serious.

Besides, on some small font sizes `cyrl/be` now looks very like `six=open-contour`.

Is there a reason why the shape was changed? For _russian_ cyrillic alphabet the current `cyrl/be` looks a little bit like a stranger. Did the new shape fixes some other cyrillic alphabet (Belorussian, Ukrainian, etc)?

Is it possible to get the old shape somehow? Revert the commit, introduce a parameter (similar to `onumZeroHeightRatio`)? However I think introducing a variant for yet another non-latin letter would be an overhead.

Isn't there a similar issue for `grek/delta`?

**Comment by be5invis** [comment]
Did some rebalance and it now looks better. Note that there are many fonts that used small ring for `б`.

![image](https://user-images.githubusercontent.com/240091/109108290-131ba080-76e8-11eb-9aa6-ada4f110a76b.png)

**Comment by pv4** [comment]
@be5invis 

> Note that there are many fonts that used small ring for `б`.

Yes, I saw them. But their ring doesn't differ from x-height as much as the previous Iosevka variant did. And the _most_ of fonts still have x-height ring.

Anyway, the current variant is fine. It's much better. Thanks!

**Comment by VladWinner** [comment]
> And the _most_ of fonts still have x-height ring.

@pv4 Just because x-height "б"-ring (or rather an oval) is implement in a certain number of fonts doesn't mean that this fonts represent Cyrillic letter "б" fully correctly. Don't take it as an insult. We need to go deeper.
I recommend you to watch the video "[How to learn to distinguish correct Cyrillic alphabet in fonts and incorrect one. Letter "Б"/be](https://www.youtube.com/watch?v=7-bgbI0b37g)" (in Russian) created by Paratype Art Director and PT Mono's Designer Alexandra Korolkova.
Next are the professional's comments from video in the link above:
![image](https://user-images.githubusercontent.com/13555921/118413728-70047280-b6a9-11eb-8db7-e4337c9d78df.png)

> 2:59 "б" in this place (top point of "б"-oval) does not have such an overhang as the letter "o"
3:07 "о" must be higher than "б" (for contrast — distribution of visual space between tail and oval)
3:17 "б" has an oval thing with growing tail on left side, oval top point height approximately the same as lowercase glyphs height.

![image](https://user-images.githubusercontent.com/13555921/118414032-0be2ae00-b6ab-11eb-9481-133cee353068.png)

> 15:19 We are forced to do "б"-oval below than letter "o" to perform optical compensation otherwise there will not be enough white [free] space (in bold styles)

That is, if we proceed from correct logic of height in Cyrillic ("б"-oval ≈ x-height < "o"), then you are certainly right, but given amount of Iosevka font styles, this is a forced measure. 
![image](https://user-images.githubusercontent.com/13555921/118415275-1eacb100-b6b2-11eb-813f-20344216503b.png)

@be5invis An ideal compromise would be the equation of "б"-oval with x-height, but in non-bold styles only (maybe from light to regular). This method is used in PT Mono and IBM Plex Mono which contain a high-quality realization of the Cyrillic alphabet's peculiarity. But I am not really sure that it is possible to implement this within current Iosevka files generation logic.
![image](https://user-images.githubusercontent.com/13555921/118414618-6598a780-b6ae-11eb-947f-cc7bc39e655d.png)

**Comment by pv4** [comment]
@VladWinner thanks for the link, I'll definitely watch it when I have time.

But WRT PT fonts I would not trust their creators 100%. I used PT Mono for some time but had switched to another font because in PT Mono different letters looked inconsistent in term of serifs. Latin uppercase `L` has a single serif (and I would call it a stylistic feature rather than a serif) while cyrillic uppercase `Г` has full set of serifs in spite of these both having similar shapes. Moreover, while cyrillic uppercase `Г` has full set of serifs, the similar `П` has no serifs at all. Such inconsistencies also appeared in latin letters. They were so unpleasant for me that I stopped using PT Mono and switched to something another. A few years later I finally found Iosevka.

**Comment by VladWinner** [comment]
@pv4 
**[Offtop]**
In fact, PT Mono is a reincarnation of Droid Sans Mono, which had no serifs. Russian designers use serifs in the most similar letters only, not everywhere. I assume that this serifs choice is also due to use font in password input field on websites. It is also interesting that the authors themselves did not promote PT Mono for programming purposes.
If you look at "[legibility test](https://github.com/be5invis/Iosevka/blob/master/sample-text/legibility-test-matrix.txt)" file, probably you will understand why serifs in Latin `L` and Cyrillic `Г` is different in this font.
**[/Offtop]**
