### ISSUE TITLE
Any way to get smaller file sizes?

### ISSUE THREAD

**Issue by jonpalmisc** [be5invis/Iosevka#916]
**Is your feature request related to a problem? Please describe.**
Due to the size of Iosevka's web font files (~.5 MB per weight), they take a moment to load even on fast connections, resulting in a flash of unstyled text.

**Describe the solution you'd like**
A lighter weight or minimal distribution that is more optimized for performance

**Describe alternatives you've considered**
Using a different font

**Additional context**
I apologize if this is an ignorant question or if I am misunderstanding something. Please let me know if there is a way I can integrate Iosevka into my site in a more performant way, as it is truly a excellent font

**Comment by jonpalmisc** [comment]
Update: I found an older issue about this which requires building the font yourself. Normally I wouldn't be opposed to this, but because of the extreme size of the repo, it is quite the process. My `git clone` operation got to around 700 MB before just slowing to a halt.

It would be nice to have a "performance optimized" build included in the releases section. I'm sure many people including myself would benefit greatly from it.

**Comment by be5invis** [comment]
Git could do a shallow clone.
And you could do subsetting using `pyftsubset` tool from FontTools.
Maybe there could be release packages contain only ASCII...

**Comment by jonpalmisc** [comment]
A shallow clone worked. This is the config I am currently using, which produces WOFF2 files at around 250kb each:

```
[buildPlans.iosevka-custom]
family = "Iosevka Custom"
spacing = "normal"
serifs = "sans"
no-cv-ss = true

[buildPlans.iosevka-custom.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.iosevka-custom.weights.bold]
shape = 700
menu = 700
css = 700

  [buildPlans.iosevka-custom.slopes]
  upright = "normal"
```

Are there any settings you'd recommend I add to cut down the size further?

**Comment by be5invis** [comment]
@jonpalmisc You can use tools like `pyftsubset` to further subset the fonts to just contain the characters you needed.

**Comment by num-lock** [comment]
Hi, I found this issue because I face the same problem.

I tried subsetting the font (iosevka-regular.ttf) with `pyftsubset` to the latin subset **(*)** and converting it to woff2 in one go. The resulting file size is still 90kB. In comparison Roboto Mono for example is only 16kB and most other fonts are in that range as well with some going up to high 30s of kBs when subsetting them to just latin character set.

Are there any other steps one could use to reduce the size and make it more attractive as a webfont?

**(*)** Unicode range is `U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+2000-206F,U+2074,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD` for anyone interested.
