### ISSUE TITLE
Improving Cyrillic alphabet letters

### ISSUE THREAD

**Issue by VladWinner** [be5invis/Iosevka#922]
- [✓] The requested variant shape does not go too far away from Iosevka's design.
- [✓] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [✓] At least two monospace/programming fonts, created by different designers, supported the requested variant. Provide images below.

------

I have displayed in screenshots the most successful elements of Cyrillic letters from other fonts that can be realised for Iosevka. Similar Latin letters are highlighted in cyan.

------
![iosevka1](https://user-images.githubusercontent.com/13555921/112046109-a9fb4180-8b5c-11eb-98a7-013c4ceae3ab.png)
![iosevka2](https://user-images.githubusercontent.com/13555921/112046267-dd3dd080-8b5c-11eb-8706-03e0a186c8a0.png)

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/112086861-37816600-8b4a-11eb-9b0a-8d7ac6e38a50.png)
Status so far

**Comment by pv4** [comment]
@VladWinner are you sure `soft sign` (`ь`) should look like that?

It now looks like non-italic `hard sign` (`ъ`). It's beautiful but less readable than the original variant. I'd revert the changes of both of these and `y` (`ы`).

@be5invis if you consider modifying cyrillic italic, then the changes on the attached image would be nice to have too. The changes are for `ь`, `ъ`, `ы` to have rounded left bottom part instead of cornered.

![image](https://user-images.githubusercontent.com/2502094/112142545-a1dbea00-8bce-11eb-9d59-bc83c69707c7.png)

**Comment by be5invis** [comment]
@pv4 Not realized that yet — hold on.

**Comment by NoxUltima** [comment]
We should do the same for the Serbian љ (lje) and њ (nje) too. They're just ligatures of l and n with the soft sign.

**Comment by VladWinner** [comment]
@pv4 Hello. I would generally prefer to remove any serifs from `soft sign` (`ь`) (as in IBM Plex Mono or Input Serif) in all style variations to get rid of visual confusion with `hard sign` (`ъ`) as much as possible, but in this case the letter `ь` will not correspond to "slab" style of Etoile and then we'll have to rethink even more letters. It should also be noted that `hard sign` is much less common in words than `soft sign` (at least in Russian language), so it is much easier to remember this appearance of `ь`.
Also I support the idea of rounded left bottom part, which is why I highlighted these fonts in the screenshot.

**Comment by pv4** [comment]
@VladWinner

> I would generally prefer to remove any serifs from `soft sign` (`ь`) [...] to get rid of visual confusion with `hard sign` (`ъ`)

I think the current implementation (v5.0.9) is already fine with that. Unlike the fonts you presented **Iosevka has both `slab` and `sans` variants**, so the ideal case is when `ь` and `ъ` are visually easily distinguishable from each other and from their `slab` variants.

> `hard sign` is much less common in words than `soft sign`

I agree but that doesn't mean their being hardly distinguishable is acceptable in situation where we already had variants that are good. I still think `ь` and `ъ` have much better/readable look in v5.0.9.

**Comment by VladWinner** [comment]
@be5invis @pv4 I think this solution will be the most advantageous.
![image](https://user-images.githubusercontent.com/13555921/112213414-1c3c5680-8c2f-11eb-8aa6-a59a83558dda.png)
I used curves from other letters (`в`+`е`+`и`→`ы`; `з`→ `ъ` serif),  for new variant.

This variant of the italics for `ы` is used when handwriting:
![image](https://user-images.githubusercontent.com/13555921/112211475-fd3cc500-8c2c-11eb-825f-d94b89f5cbde.png)

**Comment by pv4** [comment]
> I think this solution will be the most advantageous.

@VladWinner I'm sorry, but I disagree. I still prefer the current (v5.0.9) style of "top serifs" of hard/soft signs :( What are the benefits of making `soft sign` looking like you suggest?

@be5invis btw the circle part of these 3 glyphs should be like in latin `b=toothless-rounded` (I think @VladWinner will agree with me here). So, not only the left bottom part of the circle should be rounded, but the left top part too. On all the previous images this part was incorrect (it's ok for upright though).

![image](https://user-images.githubusercontent.com/2502094/112229769-8652fc80-8c2b-11eb-9659-86442281c2ba.png)

@be5invis you should know that better than me, but I'll write it anyway. PLEASE keep in mind that the font look should be generic/universal and readable for all users. When @NoxUltima suggested tons of new (fancy?) variants for latin glyphs, those were just variants which a user could choose not to use.

In this thread we're talking about making design for the only variant (unless you wish to make variants for glyphs specific to cyrillic). If it will have some fancy look (like an example from "Victor Mono") all users will have to live with that. E.g. I personally don't like the current latin cursive `x` because it's not "Iosevka visual style" and it looks strange when reading a word containing it among "Iosevka visual style" glyphs. But I can just disable it and live with `x=curly` or `x=straight`.

Well, what I'd like to say, please, be careful when making questionable changes (like serifed `ь` looking like serifless `ъ`, but not only that). I KNOW you'll choose the right way. I just hope, I will like the way you choose.

@be5invis also please stop me if I write anything I must not. It's your project.

@VladWinner I'm sorry if I look rude, it was not my intention. I do NOT want to make you away from contributing to Iosevka just because I'm rude. Keep in mind please that for Iosevka I'm just another average user, exactly like you. I don't develop, I don't commit. Your point of view is as important as mine.

**Comment by NoxUltima** [comment]
Well on my standpoint they aren't that "fancy".

Sometimes I try to argue my points out, such as the backslash and then ended up failing with a "justification" mark.

I think I may have to close the topic on looped letters.

**Comment by be5invis** [comment]
Sans:
![image](https://user-images.githubusercontent.com/240091/112239594-fe0d3100-8c03-11eb-82dc-5fffc7e613b5.png)


Slab:
![image](https://user-images.githubusercontent.com/240091/112239569-f188d880-8c03-11eb-97b5-bbf4b46014f5.png)


Etoile:
![image](https://user-images.githubusercontent.com/240091/112239545-e9309d80-8c03-11eb-9bb8-c2cd8278aadb.png)

**Comment by be5invis** [comment]
All the `ь`-related glyphs will be round in Sans' italics and become even more cursive in Slab's italics.

**Comment by NoxUltima** [comment]
Looks nice, but I think we should also get rid of the serifs on Cyrillic &mcy; and &ncy; for Sans/Aile italics.

**Comment by be5invis** [comment]
@NoxUltima That's fixed later

**Comment by be5invis** [comment]
Sans:
![image](https://user-images.githubusercontent.com/240091/112245277-c73c1880-8c0d-11eb-93fe-33b23ce71ce7.png)

Slab:
![image](https://user-images.githubusercontent.com/240091/112245292-cd31f980-8c0d-11eb-9eab-519b2f53f01b.png)

Etoile:
![image](https://user-images.githubusercontent.com/240091/112245306-d4f19e00-8c0d-11eb-9370-b31803d3e424.png)

**Comment by NoxUltima** [comment]
There we go

**Comment by pv4** [comment]
@be5invis When using `cyrl-yeri=round`, the right vertical bar has non-italic serifs. The attached patch seems to fix it. Is it a bug?

```patch
diff -Napur Iosevka-dev.orig/font-src/glyphs/letter/cyrillic/yeri.ptl Iosevka-dev/font-src/glyphs/letter/cyrillic/yeri.ptl
--- Iosevka-dev.orig/font-src/glyphs/letter/cyrillic/yeri.ptl   2021-03-27 17:13:26.000000000 +0300
+++ Iosevka-dev/font-src/glyphs/letter/cyrillic/yeri.ptl        2021-03-28 04:12:16.114469216 +0300
@@ -130,10 +130,10 @@ glyph-block Letter-Cyrillic-Yeri : begin
                        jut -- jut
                include : VBarRight df.rightSB 0 top df.mvs
                if SLAB : begin
-                       include : tagged 'serifRT' : if (Yeri === CyrlYeriCursiveShape)
+                       include : tagged 'serifRT' : if (Yeri !== CyrlYeriUprightShape)
                                then : glyph-proc
                                else : CenterTopSerif (df.rightSB - df.mvs / 2 * HVContrast) top jut
-                       include : tagged 'serifRB' : if (Yeri === CyrlYeriCursiveShape)
+                       include : tagged 'serifRB' : if (Yeri !== CyrlYeriUprightShape)
                                then : RightwardBottomSerif df.rightSB 0 (jut - 0.5 * df.mvs * HVContrast)
                                else : CenterBottomSerif (df.rightSB - df.mvs / 2 * HVContrast) 0 jut

```

**Comment by be5invis** [comment]
@pv4 Fixed

**Comment by pv4** [comment]
@be5invis Thanks!

> `cyrl-yeri` is not tagged

Does it mean I'm not supposed to choose non-default variants there when building using custom parameters? I mean, is changing the variants for `cyrl*yeri` "officially supported"?

**Comment by be5invis** [comment]
> I mean, is changing the variants for cyrl*yeri "officially supported"?

They are not considered supported, just like changing `parameters.toml`.

**Comment by VladWinner** [comment]
@be5invis Thank you for the release! Please revert back italic for `х` (kha/ha). In Latin alphabet the same letter `x` has not changed in the italic in same way (looks like an unintentional mistake/bug).

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/112757325-36af6080-8f9e-11eb-8d77-01818e6dcc8e.png)
This is also added now.

**Comment by be5invis** [comment]
Closing as fixed.

**Comment by VladWinner** [comment]
Rendering issue with `щ` in 6.0.0-preview.1
Iosevka — Monospace, Default — Italic ✓
![image](https://user-images.githubusercontent.com/13555921/114317409-a4b46580-9b10-11eb-96ba-c6102c741f2c.png)
Iosevka Slab — Monospace, Slab-serif — Italic ✓
![image](https://user-images.githubusercontent.com/13555921/114317505-12609180-9b11-11eb-950b-3250fe188a03.png)
Iosevka SS16 — Monospace, PT Mono Style — Italic ×
![image](https://user-images.githubusercontent.com/13555921/114317470-eb09c480-9b10-11eb-8e2d-e7fbed5bdf48.png)
