### ISSUE TITLE
Disable symbols

### ISSUE THREAD

**Issue by aymanbagabas** [be5invis/Iosevka#930]
I'm trying to use Iosevka Etoile in my websites but I've encountered an issue where Iosevka doesn't play nice with emojis. Some emojis (precisely the ones defined in [misc. symbols](https://typeof.net/Iosevka/specimen)) render as glyphs instead of colored emoji icons. For instance, ☺️ ☹️ these two render as glyphs instead of emojis, meanwhile 🙂 😃 render as emojis.

A possible solution is to have an option to disable symbols `no-symbols` or something. I'm not sure if this is a system-specific issue or perhaps I'm missing certain fonts in my system. I'm running macOS big sure if that helps.

Thank you.

**Comment by be5invis** [comment]
There are options to exclude characters, for example

```toml
[buildPlans.iosevka-custom.exclude-chars]
ranges = [[10003, 10008]]
```

**Comment by alexeyten** [comment]
Actually, one should use `U+FE0F` (aka Variation Selector-16) after misc symbol to choose it's emoji representation instead of default one.

https://unicode-table.com/en/FE0F/
https://tonsky.me/blog/emoji/#variation-selector-16

![image](https://user-images.githubusercontent.com/44377/113113225-bf363700-9212-11eb-9402-cd9ebb235e14.png)

![image](https://user-images.githubusercontent.com/44377/113113289-ceb58000-9212-11eb-99cd-2fbbdc36c037.png)

**Comment by alexeyten** [comment]
Another idea is to use [unicode-range](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/unicode-range) to exclude misc symbols from Iosevka font range.

**Comment by be5invis** [comment]
Yes using `unicode-range` in web fonts could also resolve this issue. Closing.
